# Generated by Django 3.0.5 on 2024-01-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado_Atendido_TMA',
            fields=[
                ('num_chamado', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_usu', models.CharField(blank=True, max_length=70, null=True)),
                ('desc_topico', models.CharField(blank=True, max_length=80, null=True)),
                ('desc_sub_topico', models.CharField(blank=True, max_length=80, null=True)),
                ('aberto_em', models.DateTimeField(blank=True, null=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('sla', models.IntegerField()),
                ('data_sla', models.DateTimeField(blank=True, null=True)),
                ('login_atendente', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'op_ti_chamados_atendidos_tma',
                'managed': True,
            },
        ),
    ]
