# Generated by Django 3.0.5 on 2024-01-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti_tma_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado_atendido_tma',
            name='horas_atendimento',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
