# Generated by Django 3.0.5 on 2024-08-30 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_app', '0005_liberacao_usuario_projeto_benner_cod_empresa'),
        ('estrut_org_app', '0004_filial_tem_calculo_rv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo_Despesas',
            fields=[
                ('cod_arq_despesa', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome_arq_imp', models.CharField(max_length=100)),
                ('nome_arq_original', models.CharField(max_length=100)),
                ('competencia_informada', models.DateField(blank=True, null=True)),
                ('qtd_registros', models.IntegerField()),
                ('qtd_importados', models.IntegerField()),
                ('qtd_atualizados', models.IntegerField()),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_gente_gestao_rateio_unimed_arquivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Despesa_Unimed',
            fields=[
                ('cod_despesa_unimed', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('competencia', models.CharField(max_length=50)),
                ('nome_beneficiario', models.CharField(max_length=100)),
                ('cpf_beneficiario', models.CharField(max_length=20)),
                ('tipo_depencencia', models.CharField(max_length=40)),
                ('nome_titular', models.CharField(blank=True, max_length=80, null=True)),
                ('cpf_titular', models.CharField(blank=True, max_length=20, null=True)),
                ('desc_despesa', models.CharField(blank=True, max_length=40, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('matricula_titular', models.IntegerField(blank=True, null=True)),
                ('nome_titular_senior', models.CharField(max_length=100)),
                ('cod_projeto_senior', models.CharField(max_length=30)),
                ('desc_projeto_senior', models.TextField(blank=True, max_length=255, null=True)),
                ('cod_filial_senior', models.IntegerField(blank=True, null=True)),
                ('desc_filial_senior', models.TextField(blank=True, max_length=50, null=True)),
                ('cod_empresa_senior', models.IntegerField(blank=True, null=True)),
                ('cod_arq_despesa', models.ForeignKey(db_column='cod_arq_despesa', on_delete=django.db.models.deletion.DO_NOTHING, to='gente_gestao_rateio_unimed_app.Arquivo_Despesas')),
                ('cod_projeto', models.ForeignKey(db_column='cod_projeto', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Projeto')),
            ],
            options={
                'db_table': 'op_gente_gestao_rateio_unimed_despesas',
                'managed': True,
            },
        ),
    ]
