# Generated by Django 3.0.5 on 2024-08-30 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safety_checks_aplicados_app', '0002_auto_20240830_1457'),
        ('estrut_org_app', '0004_filial_tem_calculo_rv'),
        ('safety_gab_op_emp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empilhadeira',
            fields=[
                ('cod_emp', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=40)),
                ('desc_placa', models.CharField(max_length=100)),
                ('ano_placa', models.CharField(max_length=40)),
                ('modelo_placa', models.CharField(max_length=40)),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_safe_empilhadeiras',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Modelo_Emp',
        ),
        migrations.DeleteModel(
            name='Tipo_Operacao_Emp',
        ),
        migrations.RenameField(
            model_name='gabarito_operacional_emp',
            old_name='cod_modelo_empilhadeira',
            new_name='tipo_operador',
        ),
        migrations.RemoveField(
            model_name='gabarito_operacional_emp',
            name='santos_deep_ogmo',
        ),
        migrations.AddField(
            model_name='gabarito_operacional_emp',
            name='cod_check_aplicado',
            field=models.ForeignKey(blank=True, db_column='cod_check_aplicado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='safety_checks_aplicados_app.Check_Aplicado'),
        ),
        migrations.AlterField(
            model_name='gabarito_operacional_emp',
            name='cod_avaliador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gabarito_operacional_emp',
            name='cod_empilhadeira',
            field=models.ForeignKey(blank=True, db_column='cod_empilhadeira', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='safety_gab_op_emp_app.Empilhadeira'),
        ),
    ]
