# Generated by Django 3.0.5 on 2024-03-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela_Preco_Veic',
            fields=[
                ('cod_tab_precos', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_tabela', models.CharField(max_length=80)),
                ('site_inst', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'op_frota_tab_preco_veic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Veiculo_Venda',
            fields=[
                ('cod_veic', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('handle_veic', models.IntegerField()),
                ('placa', models.CharField(max_length=10)),
                ('status_venda', models.CharField(default='N', max_length=1)),
                ('tipo_veic', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=25)),
                ('ano', models.IntegerField()),
                ('data_venda', models.DateField(blank=True, null=True)),
                ('val_venda', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('handle_cliente', models.IntegerField(blank=True, null=True)),
                ('nome_cliente', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'op_frota_veic_venda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Veiculo_Venda_Tab',
            fields=[
                ('cod_veic_venda_tab', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('tipo_veic', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=25)),
                ('ano', models.IntegerField()),
                ('cod_tab_precos', models.ForeignKey(db_column='cod_tab_precos', on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Tabela_Preco_Veic')),
            ],
            options={
                'db_table': 'op_frota_veic_venda_tab',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Preco_Veic_Tab',
            fields=[
                ('cod_preco_veic_tab', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('competencia', models.DateField(blank=True, null=True)),
                ('val_comp', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('cod_veic_venda_tab', models.ForeignKey(db_column='cod_veic', on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Veiculo_Venda_Tab')),
            ],
            options={
                'db_table': 'op_frota_preco_veic_tab',
                'managed': True,
            },
        ),
    ]
