# Generated by Django 3.0.5 on 2024-03-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota_vendas_veic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo_venda_tab',
            name='codigo_veic_tab',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
