# Generated by Django 3.0.5 on 2024-03-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frota_vendas_veic_app', '0002_veiculo_venda_tab_codigo_veic_tab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo_venda',
            old_name='handle_cliente',
            new_name='eixo',
        ),
        migrations.RemoveField(
            model_name='veiculo_venda',
            name='status_venda',
        ),
        migrations.AddField(
            model_name='veiculo_venda',
            name='nome_filial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='veiculo_venda',
            name='num_nf_venda',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='veiculo_venda',
            name='renavam',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='veiculo_venda',
            name='status_ativo_benner',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='veiculo_venda',
            name='uf_compra',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='veiculo_venda_tab',
            name='cod_veic',
            field=models.ForeignKey(db_column='cod_veic', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Veiculo_Venda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo_venda_tab',
            name='competencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo_venda_tab',
            name='val_comp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo_venda_tab',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo_venda_tab',
            name='codigo_veic_tab',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo_venda_tab',
            name='marca',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo_venda_tab',
            name='modelo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo_venda_tab',
            name='tipo_veic',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Preco_Veic_Tab',
        ),
    ]
