# Generated by Django 3.0.5 on 2024-03-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota_vendas_veic_app', '0003_auto_20240312_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo_venda',
            name='tipo_veic',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='veiculo_venda_tab',
            name='tipo_veic',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
