# Generated by Django 3.0.5 on 2024-03-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frota_vendas_veic_app', '0004_auto_20240313_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca_Tabela_Fipe',
            fields=[
                ('cod_marca_tab_fipe', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_marca', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'op_frota_marca_tab_fipe',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='veiculo_venda_tab',
            name='modelo',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.CreateModel(
            name='Modelo_Tabela_Fipe',
            fields=[
                ('cod_modelo_tab_fipe', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_modelo', models.CharField(max_length=15)),
                ('cod_marca_tab_fipe', models.ForeignKey(db_column='cod_marca_tab_fipe', on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Marca_Tabela_Fipe')),
            ],
            options={
                'db_table': 'op_frota_modelo_tab_fipe',
                'managed': True,
            },
        ),
    ]
