# Generated by Django 3.0.5 on 2024-03-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frota_vendas_veic_app', '0005_auto_20240313_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo_venda_tab',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='veiculo_venda_tab',
            name='modelo',
        ),
        migrations.AddField(
            model_name='marca_tabela_fipe',
            name='cod_tab_precos',
            field=models.ForeignKey(blank=True, db_column='cod_tab_precos', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Tabela_Preco_Veic'),
        ),
        migrations.AddField(
            model_name='veiculo_venda_tab',
            name='cod_modelo_tab_fipe',
            field=models.ForeignKey(blank=True, db_column='cod_modelo_tab_fipe', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Modelo_Tabela_Fipe'),
        ),
    ]
