# Generated by Django 3.0.5 on 2024-04-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frota_vendas_veic_app', '0006_auto_20240322_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca_Tab_Precos',
            fields=[
                ('cod_marca_tab_precos', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_marca', models.CharField(max_length=15)),
                ('cod_tipo_veic_tab_precos', models.ForeignKey(blank=True, db_column='cod_tipo_veic_tab_precos', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Tabela_Preco_Veic')),
            ],
            options={
                'db_table': 'op_frota_marca_tab_precos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modelo_Tab_Precos',
            fields=[
                ('cod_modelo_tab_precos', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_modelo', models.CharField(max_length=15)),
                ('cod_marca_tab_precos', models.ForeignKey(db_column='cod_marca_tab_precos', on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Marca_Tab_Precos')),
            ],
            options={
                'db_table': 'op_frota_modelo_tab_precos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Veiculo_Venda_Tab_Precos',
            fields=[
                ('cod_veic_venda_tab', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('codigo_veic_tab', models.CharField(blank=True, max_length=10, null=True)),
                ('competencia', models.DateField(blank=True, null=True)),
                ('val_comp', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('cod_modelo_tab_precos', models.ForeignKey(blank=True, db_column='cod_modelo_tab_precos', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Modelo_Tab_Precos')),
                ('cod_veic', models.ForeignKey(db_column='cod_veic', on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Veiculo_Venda')),
            ],
            options={
                'db_table': 'op_frota_veic_venda_tab_precos',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='modelo_tabela_fipe',
            name='cod_marca_tab_fipe',
        ),
        migrations.RemoveField(
            model_name='veiculo_venda_tab',
            name='cod_modelo_tab_fipe',
        ),
        migrations.RemoveField(
            model_name='veiculo_venda_tab',
            name='cod_tab_precos',
        ),
        migrations.RemoveField(
            model_name='veiculo_venda_tab',
            name='cod_veic',
        ),
        migrations.DeleteModel(
            name='Marca_Tabela_Fipe',
        ),
        migrations.DeleteModel(
            name='Modelo_Tabela_Fipe',
        ),
        migrations.DeleteModel(
            name='Veiculo_Venda_Tab',
        ),
    ]
