# Generated by Django 3.0.5 on 2024-04-04 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frota_vendas_veic_app', '0007_auto_20240404_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca_tab_precos',
            name='cod_tipo_veic_tab_precos',
            field=models.ForeignKey(db_column='cod_tipo_veic_tab_precos', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Tabela_Preco_Veic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelo_tab_precos',
            name='desc_modelo',
            field=models.CharField(max_length=300),
        ),
    ]
