# Generated by Django 3.0.5 on 2024-04-04 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frota_vendas_veic_app', '0008_auto_20240404_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Veic_Tab_Precos',
            fields=[
                ('cod_tipo_veic_tab_precos', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_tipo_veic', models.CharField(max_length=15)),
                ('id_tipo_veic_tab', models.IntegerField(blank=True, null=True)),
                ('cod_tab_precos', models.ForeignKey(blank=True, db_column='cod_tab_precos', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Tabela_Preco_Veic')),
            ],
            options={
                'db_table': 'op_frota_tipo_veic_tab_precos',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='marca_tab_precos',
            name='cod_tipo_veic_tab_precos',
            field=models.ForeignKey(db_column='cod_tipo_veic_tab_precos', on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Tipo_Veic_Tab_Precos'),
        ),
    ]
