# Generated by Django 3.0.5 on 2024-04-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frota_vendas_veic_app', '0009_auto_20240404_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo_venda_tab_precos',
            name='ano',
        ),
    ]
