# Generated by Django 3.0.5 on 2024-08-30 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frota_vendas_veic_app', '0010_remove_veiculo_venda_tab_precos_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Ref_Fipe_Org',
            fields=[
                ('cod_data_ref_fipe_org', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_data', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'op_frota_data_ref_fipe_org',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='veiculo_venda_tab_precos',
            name='cod_modelo_tab_precos',
        ),
        migrations.AddField(
            model_name='veiculo_venda',
            name='status_venda',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='veiculo_venda',
            name='val_compra',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='veiculo_venda_tab_precos',
            name='cod_tab_precos',
            field=models.ForeignKey(db_column='cod_tab_precos', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Tabela_Preco_Veic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo_venda_tab_precos',
            name='data_atualizacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo_venda_tab_precos',
            name='perc_sug_venda',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='veiculo_venda_tab_precos',
            name='val_sug_venda',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo_venda_tab_precos',
            name='val_comp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Ano_Modelo_Tab_Precos',
            fields=[
                ('cod_ano_modelo_tab', models.IntegerField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('cod_modelo_tab_precos', models.ForeignKey(blank=True, db_column='cod_modelo_tab_precos', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Modelo_Tab_Precos')),
            ],
            options={
                'db_table': 'op_frota_ano_modelo_tab_precos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ano_Modelo_Historico_Tab_Precos',
            fields=[
                ('cod_ano_modelo_hist_preco', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('competencia', models.DateField(blank=True, null=True)),
                ('val_comp', models.IntegerField(blank=True, null=True)),
                ('data_atualizacao', models.DateField(blank=True, null=True)),
                ('cod_ano_modelo_tab', models.ForeignKey(blank=True, db_column='cod_ano_modelo_tab', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Ano_Modelo_Tab_Precos')),
            ],
            options={
                'db_table': 'op_frota_ano_modelo_historico_tab_precos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='veiculo_venda_tab_precos',
            name='cod_ano_modelo_tab',
            field=models.ForeignKey(blank=True, db_column='cod_ano_modelo_tab', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frota_vendas_veic_app.Ano_Modelo_Tab_Precos'),
        ),
    ]
