# Generated by Django 3.0.5 on 2024-07-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estrut_org_app', '0003_projeto_cod_reduzido_benner'),
        ('usuario_app', '0003_auto_20231110_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Gut',
            fields=[
                ('cod_item_gut', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=40)),
                ('peso', models.IntegerField()),
                ('ativo', models.CharField(default='S', max_length=1)),
                ('tipo', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'op_ti_comitec_item_guti',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ideia',
            fields=[
                ('cod_ideia', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('cod_area_senior', models.IntegerField()),
                ('desc_area_senior', models.CharField(max_length=80)),
                ('cod_chamado', models.IntegerField()),
                ('data_lancamento_idea', models.DateField(auto_now_add=True)),
                ('data_nota_gut', models.DateField(blank=True, null=True)),
                ('data_nota_head', models.DateField(blank=True, null=True)),
                ('desc_ideia', models.CharField(max_length=500)),
                ('val_ganhos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('val_despesas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('horas_ganhas', models.IntegerField(blank=True, default=0, null=True)),
                ('obs', models.CharField(blank=True, max_length=300, null=True)),
                ('cod_status', models.IntegerField()),
                ('obs_head', models.CharField(blank=True, max_length=300, null=True)),
                ('nota_head', models.IntegerField(blank=True, default=0, null=True)),
                ('cod_empresa', models.ForeignKey(blank=True, db_column='cod_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Empresa')),
                ('cod_gut_g', models.ForeignKey(blank=True, db_column='cod_gut_g', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cod_gut_g', to='ti_comitec_app.Item_Gut')),
                ('cod_gut_t', models.ForeignKey(blank=True, db_column='cod_gut_t', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cod_gut_t', to='ti_comitec_app.Item_Gut')),
                ('cod_gut_u', models.ForeignKey(blank=True, db_column='cod_gut_u', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cod_gut_u', to='ti_comitec_app.Item_Gut')),
                ('cod_usu_dono_ideia', models.ForeignKey(blank=True, db_column='cod_usu_dono_ideia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cod_usu_dono_ideia', to='usuario_app.Usuario')),
                ('cod_usu_head', models.ForeignKey(blank=True, db_column='cod_usu_head', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cod_usu_head', to='usuario_app.Usuario')),
                ('cod_usu_master', models.ForeignKey(blank=True, db_column='cod_usu_master', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cod_usu_master', to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_ti_comitec_ideias',
                'managed': True,
            },
        ),
    ]
