# Generated by Django 3.0.5 on 2024-09-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estrut_org_app', '0004_filial_tem_calculo_rv'),
        ('usuario_app', '0005_liberacao_usuario_projeto_benner_cod_empresa'),
        ('ti_comitec_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideia',
            old_name='obs',
            new_name='obs_usu_head',
        ),
        migrations.RenameField(
            model_name='ideia',
            old_name='obs_head',
            new_name='obs_usu_master',
        ),
        migrations.RemoveField(
            model_name='ideia',
            name='cod_area_senior',
        ),
        migrations.RemoveField(
            model_name='ideia',
            name='cod_empresa',
        ),
        migrations.RemoveField(
            model_name='ideia',
            name='cod_usu_dono_ideia',
        ),
        migrations.RemoveField(
            model_name='ideia',
            name='desc_area_senior',
        ),
        migrations.AddField(
            model_name='ideia',
            name='cod_atividade',
            field=models.ForeignKey(blank=True, db_column='cod_atividade', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Atividade'),
        ),
        migrations.AddField(
            model_name='ideia',
            name='cod_usu_owner',
            field=models.ForeignKey(blank=True, db_column='cod_usu_owner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cod_usu_owner', to='usuario_app.Usuario'),
        ),
        migrations.AddField(
            model_name='ideia',
            name='obs_usu_owner',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ideia',
            name='resumo_ideia',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_gut',
            name='color_flag',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='item_gut',
            name='flag',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterModelTable(
            name='item_gut',
            table='op_ti_comitec_item_gut',
        ),
    ]
