# Generated by Django 3.0.5 on 2024-08-30 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_app', '0005_liberacao_usuario_projeto_benner_cod_empresa'),
        ('estrut_org_app', '0004_filial_tem_calculo_rv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param_RV_Van',
            fields=[
                ('cod_param_rv_van', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_ini', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('cargo', models.IntegerField()),
                ('fator', models.IntegerField()),
                ('val_caixaria', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('val_entrega', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('tipo_recarga', models.IntegerField()),
                ('val_recarga', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_conecta_param_rv_vans',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Registro_2art_Van',
            fields=[
                ('cod_reg_2art_van', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField(null=True)),
                ('entrega', models.CharField(max_length=20, null=True)),
                ('cargaatual', models.CharField(max_length=20, null=True)),
                ('frota', models.CharField(max_length=20, null=True)),
                ('placa', models.CharField(max_length=10, null=True)),
                ('mapa', models.CharField(max_length=10, null=True)),
                ('entregas', models.CharField(max_length=5, null=True)),
                ('cxcarreg', models.CharField(max_length=10, null=True)),
                ('cxentreg', models.CharField(max_length=10, null=True)),
                ('hrsai', models.CharField(max_length=25, null=True)),
                ('hrentr', models.CharField(max_length=25, null=True)),
                ('qtentregascarregrv', models.CharField(max_length=5, null=True)),
                ('qtentregasentregrv', models.CharField(max_length=5, null=True)),
                ('indicedeventregasrv', models.CharField(max_length=15, null=True)),
                ('fator', models.CharField(max_length=5, null=True)),
                ('matricula_colab', models.CharField(max_length=10, null=True)),
                ('cpf_colab', models.CharField(max_length=15, null=True)),
                ('funcao', models.IntegerField(blank=True, null=True)),
                ('alteracao', models.IntegerField(blank=True, null=True)),
                ('cod_param_rv_van', models.ForeignKey(db_column='cod_param_rv_van', on_delete=django.db.models.deletion.DO_NOTHING, to='conecta_vans_app.Param_RV_Van')),
                ('cod_projeto', models.ForeignKey(db_column='cod_projeto', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Projeto')),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_conecta_2art_vans',
                'managed': True,
            },
        ),
    ]
