# Generated by Django 3.0.5 on 2023-03-02 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    '''   dependencies = [
        ('app_proj_gerencial_v1', '0012_auto_20230302_1031'),
    ]'''

    operations = [
        migrations.CreateModel(
            name='Notas_Tratadas',
            fields=[
                ('cod_nota_tratada', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('handle_empresa', models.IntegerField()),
                ('nome_empresa', models.CharField(max_length=50)),
                ('handle_filial', models.IntegerField(blank=0)),
                ('nome_filial', models.CharField(max_length=70)),
                ('numero_nota', models.IntegerField()),
                ('serie', models.IntegerField(blank=True, null=True)),
                ('chave_nota', models.CharField(max_length=44)),
                ('natureza', models.CharField(blank=True, max_length=60, null=True)),
                ('emissao', models.DateField()),
                ('doc_fornec', models.CharField(max_length=19)),
                ('nome_fornec', models.CharField(max_length=60, null=True)),
                ('justificativa', models.CharField(max_length=300)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING,
                                              to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_contabil_notas_tratadas',
                'managed': True,
            },
        ),
    ]
