# Generated by Django 3.0.5 on 2023-03-02 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('app_proj_gerencial_v1', '0013_auto_20230302_1654'),
        ('contabil_operacoes_farol_ndd_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excecoes_Natureza_Operacao',
            fields=[
                ('cod_excecao_operacao', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_operacao', models.CharField(blank=True, max_length=60, null=True)),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_contabil_excecoes_natureza_operacao',
                'managed': True,
            },
        ),
    ]
