# Generated by Django 3.0.5 on 2023-08-09 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_app', '0001_initial'),
        ('frota_importa_2art_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemuracaoVariavel2Art',
            fields=[
                ('cod_2art_rem_var', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('placa_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('mapa_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('entrega_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('carga_atual_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('frota_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('entregas_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('cxcarreg_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('cxentreg_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('hrsai_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('hrentr_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('recarga_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('hrmatinal_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('hrjornadaliq_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('hrmetajornada_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('vlbateujornmot_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('vlnaobateujornmot_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('vlbateujornaju_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('vlnaobateujornaju_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('qtentregascarregrv_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('qtentregasentregrv_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('hrpcfisica_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('hrpcfinanceira_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('cpf_mot_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('cpf_ajud1_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('cpf_ajud2_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('status_bloqueio_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('data_bloqueio_2art_rem_var', models.DateField(null=True)),
                ('status_edicao_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('data_ultima_edicao_2art_rem_var', models.DateField(null=True)),
                ('status_liberacao_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('data_liberacao_2art_rem_var', models.DateField(null=True)),
                ('codfilial_2art_rem_var', models.CharField(max_length=50, null=True)),
                ('cod_reg_2art', models.ForeignKey(db_column='cod_reg_2art', on_delete=django.db.models.deletion.DO_NOTHING, to='frota_importa_2art_app.Registro2Art')),
                ('cod_usu_liberacao_2art_rem_var', models.ForeignKey(db_column='cod_usu_liberacao_2art_rem_var', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_gente_gestao_2art_rem_var',
                'managed': True,
            },
        ),
    ]
