# Generated by Django 3.0.5 on 2024-09-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('safety_checks_aplicados_app', '0002_auto_20240905_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gabarito_GSDPQ',
            fields=[
                ('cod_gabarito_check', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('placa_caminhao', models.CharField(max_length=20)),
                ('cod_check_aplicado', models.ForeignKey(blank=True, db_column='cod_check_aplicado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='safety_checks_aplicados_app.Check_Aplicado')),
            ],
            options={
                'db_table': 'op_safe_gsdpq',
                'managed': True,
            },
        ),
    ]
