# Generated by Django 3.0.5 on 2023-08-09 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_app', '0001_initial'),
        ('estrut_org_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gente_Gestao_Motivo_Especifico',
            fields=[
                ('cod_mot_especifico', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_motivo_especifico', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'op_geg_fluxo_punitivo_motivo_especifico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gente_Gestao_Motivo_Juridico',
            fields=[
                ('cod_mot_juridico', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_motivo_juridico', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'op_geg_fluxo_punitivo_motivo_juridico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gente_Gestao_Punicao',
            fields=[
                ('cod_punicao', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome_colab', models.CharField(max_length=150)),
                ('matricula_colab', models.IntegerField()),
                ('data_admissao', models.DateField()),
                ('cpf_colab', models.BigIntegerField()),
                ('cod_cargo_colab', models.IntegerField()),
                ('desc_cargo_colab', models.CharField(max_length=80)),
                ('situacao_colab', models.CharField(max_length=30)),
                ('penalidade', models.CharField(max_length=2)),
                ('data_ocorrencia', models.DateField()),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('desc_motivo', models.CharField(max_length=300)),
                ('ativo', models.CharField(default='S', max_length=1)),
                ('obs_punicao', models.CharField(blank=True, max_length=300, null=True)),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
                ('cod_mot_especifico', models.ForeignKey(blank=True, db_column='cod_mot_especifico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gente_gestao_fluxo_punitivo.Gente_Gestao_Motivo_Especifico')),
                ('cod_mot_juridico', models.ForeignKey(db_column='cod_mot_juridico', on_delete=django.db.models.deletion.DO_NOTHING, to='gente_gestao_fluxo_punitivo.Gente_Gestao_Motivo_Juridico')),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_geg_fluxo_punitivo_lancamentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gente_Gestao_Dias_Suspensao',
            fields=[
                ('cod_dias_suspensao', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('inicio_suspensao', models.DateField()),
                ('fim_suspensao', models.DateField()),
                ('cod_punicao', models.ForeignKey(db_column='cod_punicao', on_delete=django.db.models.deletion.DO_NOTHING, to='gente_gestao_fluxo_punitivo.Gente_Gestao_Punicao')),
            ],
            options={
                'db_table': 'op_geg_fluxo_punitivo_dias_suspensao',
                'managed': True,
            },
        ),
    ]
