# Generated by Django 3.0.5 on 2024-09-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gente_gestao_fluxo_punitivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gente_gestao_dias_suspensao',
            table='ger_gente_gestao_fluxo_punitivo_dias_suspensao',
        ),
        migrations.AlterModelTable(
            name='gente_gestao_motivo_especifico',
            table='ger_gente_gestao_fluxo_punitivo_motivo_especifico',
        ),
        migrations.AlterModelTable(
            name='gente_gestao_motivo_juridico',
            table='ger_gente_gestao_fluxo_punitivo_motivo_juridico',
        ),
        migrations.AlterModelTable(
            name='gente_gestao_punicao',
            table='ger_gente_gestao_fluxo_punitivo_punicao',
        ),
    ]
