# Generated by Django 3.0.5 on 2023-08-09 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estrut_org_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('cod_calendario', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_calendario', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('ano_calendario', models.IntegerField()),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_calendario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Calendario_Dias',
            fields=[
                ('cod_calendario_dia', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_dia', models.DateField()),
                ('dia_semana', models.IntegerField()),
                ('classificacao_dia', models.CharField(max_length=1)),
                ('qtd_dias_data_prevista_req_e', models.IntegerField(default=0)),
                ('data_prevista_req_e', models.DateField(default=None, null=True)),
                ('qtd_dias_data_prevista_req_ne', models.IntegerField(default=0)),
                ('data_prevista_req_ne', models.DateField(default=None, null=True)),
                ('qtd_dias_data_prevista_req_plan', models.IntegerField(default=0)),
                ('data_prevista_req_plan', models.DateField(default=None, null=True)),
                ('num_semana', models.IntegerField()),
                ('mes_ref_num_semana', models.IntegerField(default=0)),
                ('periodo', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('mes_competencia_periodo', models.IntegerField(default=0)),
                ('ano_competencia_periodo', models.IntegerField(default=0)),
                ('cod_calendario', models.ForeignKey(db_column='cod_calendario', on_delete=django.db.models.deletion.DO_NOTHING, to='calendario_app.Calendario')),
            ],
            options={
                'db_table': 'op_calendario_dias',
                'managed': True,
            },
        ),
    ]
