# Generated by Django 3.0.5 on 2024-08-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conecta_as_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param_rv_as',
            name='cargo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='param_rv_as',
            name='fator',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='param_rv_as',
            name='tipo_recarga',
            field=models.IntegerField(),
        ),
    ]
