# Generated by Django 3.0.5 on 2023-08-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirma_Periodo_Fechamento_Folha',
            fields=[
                ('cod_confirma_periodo_fechamento_folha', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('mes_competencia_periodo', models.IntegerField(default=0)),
                ('ano_competencia_periodo', models.IntegerField(default=0)),
                ('ativa', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'op_plan_controle_confirma_periodo_fecha_folha',
                'managed': True,
            },
        ),
    ]
