# Generated by Django 3.0.5 on 2024-08-30 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_controle_fat_2art_terc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='beneficiarioterceiro',
            table='ger_cad_beneficiario_terc',
        ),
        migrations.AlterModelTable(
            name='cadastroplacaterceiro',
            table='ger_cad_placa_terceiro',
        ),
        migrations.AlterModelTable(
            name='cadfretespot',
            table='ger_cad_frete_spot',
        ),
        migrations.AlterModelTable(
            name='histacaomapas2artterceiros',
            table='ger_2art_hist_acoes_mapas_terc',
        ),
        migrations.AlterModelTable(
            name='lancamentopagamentoextras',
            table='ger_lancamentos_pagamento_extras',
        ),
        migrations.AlterModelTable(
            name='lancamentosregistro2artterceirosfinanceiro',
            table='ger_lancamentos_registro_2art_terc_financ',
        ),
        migrations.AlterModelTable(
            name='pagamento2artterceirosfinanceiro',
            table='ger_pagamento_2art_terc_financ',
        ),
        migrations.AlterModelTable(
            name='registro2artterceirosfinanceiro',
            table='ger_2art_terceiros_financeiro',
        ),
        migrations.AlterModelTable(
            name='tipoocorrenciasfinanceiroterceiros',
            table='ger_tipo_ocor_financ_terc',
        ),
    ]
