# Generated by Django 3.0.5 on 2023-01-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vincula_Roteiro_Pecas',
            fields=[
                ('cod_roteiro_peca', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('handle_roteiro', models.IntegerField()),
                ('nome_roteiro', models.CharField(max_length=80)),
                ('handle_marca', models.IntegerField()),
                ('nome_marca', models.CharField(max_length=50)),
                ('handle_modelo', models.IntegerField()),
                ('nome_modelo', models.CharField(max_length=100)),
                ('cod_ref_item', models.CharField(max_length=30)),
                ('desc_item', models.CharField(max_length=200)),
                ('qtd', models.IntegerField()),
                ('troca', models.BooleanField()),
                ('data_lancamento', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'op_frota_vpo_vinculo_roteiro_peca',
                'managed': True,
            },
        ),
    ]
