# Generated by Django 3.0.5 on 2023-01-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota_vpo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vincula_roteiro_pecas',
            name='un_item',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
