# Generated by Django 3.0.5 on 2023-01-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota_vpo_app', '0002_vincula_roteiro_pecas_un_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vincula_roteiro_pecas',
            name='nome_roteiro',
            field=models.CharField(max_length=300),
        ),
    ]
