# Generated by Django 3.0.5 on 2023-03-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota_vpo_app', '0003_auto_20230130_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='vincula_roteiro_pecas',
            name='handle_tipo_veiculo',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vincula_roteiro_pecas',
            name='nome_tipo_veiculo',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
