# Generated by Django 3.0.5 on 2024-03-27 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_app', '0003_auto_20231110_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificativa_Compra',
            fields=[
                ('cod_justificativa_compra', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('justificativa', models.CharField(blank=True, max_length=300, null=True)),
                ('eh_ativa', models.CharField(default='S', max_length=1)),
                ('data_cad', models.DateField(auto_now_add=True)),
                ('handle_itens_compra', models.IntegerField()),
                ('cod_usu', models.ForeignKey(blank=True, db_column='cod_usu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_suprimentos_evolucao_preco_justificativas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compra_Auditada',
            fields=[
                ('cod_compra_aud', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('handle_filial_compra', models.IntegerField()),
                ('handle_itens_compra', models.IntegerField()),
                ('handle_produto', models.IntegerField()),
                ('val_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qtd_item', models.IntegerField()),
                ('data_aud', models.DateField(auto_now_add=True)),
                ('cod_usu', models.ForeignKey(blank=True, db_column='cod_usu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_suprimentos_compras_aud',
                'managed': True,
            },
        ),
    ]
