# Generated by Django 3.0.5 on 2023-08-17 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendario_app', '0001_initial'),
        ('estrut_org_app', '0001_initial'),
        ('usuario_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao_Atendida_TMA',
            fields=[
                ('cod_req_atendida_tma', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('handle_req_pai', models.IntegerField()),
                ('num_req_pai', models.IntegerField(blank=True, null=True)),
                ('data_inclusao', models.DateTimeField(blank=True, null=True)),
                ('data_confirmada', models.DateTimeField(blank=True, null=True)),
                ('data_atendida', models.DateTimeField(blank=True, null=True)),
                ('handle_usu_incluiu', models.IntegerField(blank=True, null=True)),
                ('nome_usu_incluiu', models.CharField(blank=True, max_length=50, null=True)),
                ('handle_comprador', models.IntegerField(blank=True, null=True)),
                ('nome_comprador', models.CharField(blank=True, max_length=70, null=True)),
                ('handle_familia', models.IntegerField(blank=True, null=True)),
                ('desc_familia', models.CharField(blank=True, max_length=70, null=True)),
                ('status_ordem', models.CharField(blank=True, max_length=30, null=True)),
                ('chave_busca', models.CharField(max_length=15)),
                ('status_atendimento', models.CharField(blank=True, max_length=1, null=True)),
                ('tma', models.CharField(blank=True, max_length=15, null=True)),
                ('tma_previsto', models.CharField(blank=True, max_length=15, null=True)),
                ('cod_dia_calendario', models.ForeignKey(db_column='cod_dia_calendario', on_delete=django.db.models.deletion.DO_NOTHING, to='calendario_app.Calendario_Dias')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
                ('cod_usu', models.ForeignKey(blank=True, db_column='cod_usu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_suprimentos_requisicoes_atendidas_tma',
                'managed': True,
            },
        ),
    ]
