# Generated by Django 3.0.5 on 2024-08-30 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos_tma_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requisicao_atendida_tma',
            table='ger_suprimentos_requisicoes_atendidas_tma',
        ),
    ]
