# Generated by Django 3.0.5 on 2024-01-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('safety_layout_checklist_app', '0002_auto_20231110_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('cod_colaborador', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('matricula_colaborador', models.IntegerField()),
                ('nome_colaborador', models.CharField(max_length=100)),
                ('cod_empresa', models.IntegerField()),
                ('desc_cargo', models.CharField(max_length=80)),
                ('cnh', models.CharField(max_length=20)),
                ('validade_cnh', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'op_safe_colaboradores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item_Fotos_Texto_Check_Aplicado',
            fields=[
                ('cod_item_fotos_texto_itens_checks_aplicados', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=40)),
                ('caminho_imagem', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'op_safe_itens_fotos_texto_checks_aplicados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item_Check_Aplicados',
            fields=[
                ('cod_item_ap', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('resp_item', models.DateTimeField(blank=True, null=True)),
                ('cod_item_check', models.ForeignKey(blank=True, db_column='cod_item_check', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='safety_layout_checklist_app.Item_Check')),
            ],
            options={
                'db_table': 'op_safe_itens_checks_aplicados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Check_Aplicado',
            fields=[
                ('cod_checks_aplicados', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('cod_filial', models.IntegerField()),
                ('comentarios', models.CharField(max_length=300)),
                ('data_registro', models.DateTimeField(blank=True, null=True)),
                ('cod_colaborador', models.ForeignKey(blank=True, db_column='cod_colaborador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='safety_checks_aplicados_app.Colaborador')),
                ('cod_layout_check', models.ForeignKey(blank=True, db_column='cod_layout_check', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='safety_layout_checklist_app.Layout_Check')),
            ],
            options={
                'db_table': 'op_safe_checks_aplicados',
                'managed': True,
            },
        ),
    ]
