# Generated by Django 3.0.5 on 2024-09-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safety_layout_checklist_app', '0004_auto_20240905_1509'),
        ('safety_login_colaboradores_app', '0001_initial'),
        ('safety_checks_aplicados_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano_Acao',
            fields=[
                ('cod_plano_acao', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('plano_acao', models.CharField(blank=True, max_length=300, null=True)),
                ('status_plano', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'op_safe_plano_acao',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='check_aplicado',
            old_name='cod_checks_aplicados',
            new_name='cod_check_aplicado',
        ),
        migrations.RemoveField(
            model_name='check_aplicado',
            name='cod_colaborador',
        ),
        migrations.AddField(
            model_name='check_aplicado',
            name='cod_colaborador_aplicante',
            field=models.ForeignKey(blank=True, db_column='cod_colaborador_aplicante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aplicado_por', to='safety_login_colaboradores_app.Colaborador'),
        ),
        migrations.AddField(
            model_name='check_aplicado',
            name='cod_colaborador_avaliado',
            field=models.ForeignKey(blank=True, db_column='cod_colaborador_avaliado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliado', to='safety_login_colaboradores_app.Colaborador'),
        ),
        migrations.AddField(
            model_name='item_check_aplicados',
            name='cod_check_aplicado',
            field=models.ForeignKey(db_column='cod_check_aplicado', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='safety_checks_aplicados_app.Check_Aplicado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_fotos_texto_check_aplicado',
            name='cod_check_aplicado',
            field=models.ForeignKey(db_column='cod_check_aplicado', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='safety_checks_aplicados_app.Check_Aplicado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_fotos_texto_check_aplicado',
            name='cod_item_check',
            field=models.ForeignKey(db_column='cod_item_check', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='safety_layout_checklist_app.Item_Check'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item_check_aplicados',
            name='cod_item_check',
            field=models.ForeignKey(db_column='cod_item_check', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='safety_layout_checklist_app.Item_Check'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item_check_aplicados',
            name='resp_item',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item_fotos_texto_check_aplicado',
            name='caminho_imagem',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='item_fotos_texto_check_aplicado',
            name='comentario',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
        migrations.AddField(
            model_name='plano_acao',
            name='cod_check_aplicado',
            field=models.ForeignKey(db_column='cod_check_aplicado', on_delete=django.db.models.deletion.DO_NOTHING, to='safety_checks_aplicados_app.Check_Aplicado'),
        ),
    ]
