# Generated by Django 3.0.5 on 2023-08-09 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('cod_atividade', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc1_atividade', models.CharField(max_length=30)),
                ('desc2_atividade', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'op_atividades_projeto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cod_empresa', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('handle_benner', models.IntegerField(blank=True, default=0, null=True)),
                ('handle_gn_proj_benner', models.IntegerField(blank=True, default=0, null=True)),
                ('estrutura_benner', models.CharField(blank=True, default=0, max_length=1, null=True)),
                ('cod_senior', models.IntegerField(blank=True, default=0, null=True)),
                ('desc_empresa', models.CharField(max_length=70)),
                ('data_inativado', models.DateField(null=True)),
            ],
            options={
                'db_table': 'op_empresas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('cod_filial', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('cnpj_filial', models.CharField(max_length=14, null=True)),
                ('desc_filial', models.CharField(max_length=70, null=True)),
                ('handle_benner', models.IntegerField(null=True)),
                ('estrutura_benner', models.CharField(blank=True, default=0, max_length=7, null=True)),
                ('unidade_abrev', models.CharField(max_length=3, null=True)),
                ('cod_filial_senior', models.IntegerField(null=True)),
                ('cod_promax', models.IntegerField(null=True)),
                ('cod_filial_tracking', models.IntegerField(null=True)),
                ('ativo', models.IntegerField(default=1)),
                ('regiao', models.CharField(blank=True, max_length=30, null=True)),
                ('handle_gn_proj_benner', models.IntegerField(blank=True, default=0, null=True)),
                ('cod_empresa', models.ForeignKey(db_column='cod_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Empresa')),
            ],
            options={
                'db_table': 'op_filial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OP_Estados',
            fields=[
                ('cod_estado', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'op_estados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('cod_projeto', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_proj', models.CharField(max_length=70, null=True)),
                ('cod_local_senior', models.CharField(max_length=50, null=True)),
                ('handle_benner', models.IntegerField(default=None)),
                ('cod_senior', models.IntegerField(default=None)),
                ('cod_serial_pag_terc', models.CharField(max_length=3, null=True)),
                ('ultimo_num_pagamento', models.IntegerField(null=True)),
                ('neg_aloc', models.IntegerField(null=True)),
                ('data_inativado', models.DateField(null=True)),
                ('data_inicio', models.DateField(null=True)),
                ('integra_frota', models.CharField(max_length=1, null=True)),
                ('cod_atividade', models.ForeignKey(blank=True, db_column='cod_atividade', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Atividade')),
                ('cod_empresa', models.ForeignKey(db_column='cod_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Empresa')),
                ('cod_filial', models.ForeignKey(blank=True, db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_projetos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('cod_operacao', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_operacao', models.CharField(max_length=50)),
                ('handle_gn_proj_benner', models.IntegerField(blank=True, default=0, null=True)),
                ('estrutura_benner', models.CharField(blank=True, default=0, max_length=4, null=True)),
                ('cod_empresa', models.ForeignKey(db_column='cod_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Empresa')),
            ],
            options={
                'db_table': 'op_operacoes',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='filial',
            name='cod_operacao',
            field=models.ForeignKey(db_column='cod_operacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Operacao'),
        ),
    ]
