# Generated by Django 3.0.5 on 2023-11-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrut_org_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='cod_reduzido',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='atividade',
            table='ger_atividades_projeto',
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='ger_empresa',
        ),
        migrations.AlterModelTable(
            name='filial',
            table='ger_filial',
        ),
        migrations.AlterModelTable(
            name='op_estados',
            table='ger_estados',
        ),
        migrations.AlterModelTable(
            name='operacao',
            table='ger_operacoes',
        ),
        migrations.AlterModelTable(
            name='projeto',
            table='ger_projetos',
        ),
    ]
