# Generated by Django 3.0.5 on 2024-01-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrut_org_app', '0002_auto_20231110_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='cod_reduzido_benner',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
