# Generated by Django 3.0.5 on 2024-07-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrut_org_app', '0003_projeto_cod_reduzido_benner'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='tem_calculo_rv',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
