# Generated by Django 3.0.5 on 2023-09-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_app', '0002_liberacao_usuario_projeto_benner'),
        ('estrut_org_app', '0001_initial'),
        ('frota_disponibilidade_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apontamento_Disp_Empilhadeira',
            fields=[
                ('cod_apontamento_disp_emp', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('handle_emp_benner', models.IntegerField()),
                ('placa_emp_benner', models.CharField(max_length=10)),
                ('ano_emp_benner', models.IntegerField()),
                ('modelo_emp_benner', models.CharField(blank=True, max_length=100, null=True)),
                ('placa_emp_anterior_benner', models.CharField(blank=True, max_length=10, null=True)),
                ('ativo_benner', models.CharField(max_length=1)),
                ('data_apontamento', models.DateField()),
                ('dia_semana', models.IntegerField(default=0)),
                ('turno', models.CharField(max_length=1)),
                ('status_lanc', models.CharField(default='A', max_length=1)),
                ('data_lancamento', models.DateField(auto_now_add=True)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_projeto', models.ForeignKey(db_column='cod_projeto', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Projeto')),
                ('cod_sigla', models.ForeignKey(blank=True, db_column='cod_sigla', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frota_disponibilidade_app.Sigla_Status_Disponibilidade_Frota')),
                ('cod_usu', models.ForeignKey(db_column='cod_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_frota_indisp_apontamento_empilhadeiras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OS_Apontamento_Disp_Empilhadeira',
            fields=[
                ('cod_os_apontamento_disp_emp', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('handle_os_benner', models.IntegerField()),
                ('num_os_benner', models.CharField(max_length=20)),
                ('tipo_os_benner', models.IntegerField()),
                ('data_inicial_os_benner', models.DateTimeField()),
                ('data_final_os_benner', models.DateTimeField()),
                ('handle_conjunto_manut_benner', models.IntegerField(blank=True, null=True)),
                ('desc_conj_manut_benner', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_os_benner', models.CharField(blank=True, max_length=120, null=True)),
                ('motivo', models.CharField(blank=True, max_length=300, null=True)),
                ('parada_ini_aud', models.DateTimeField(blank=True, null=True)),
                ('parada_fim_aud', models.DateTimeField(blank=True, null=True)),
                ('cod_apontamento_disp_emp', models.ForeignKey(db_column='cod_apontamento_disp_emp', on_delete=django.db.models.deletion.DO_NOTHING, to='frota_disponibilidade_empilhadeira_app.Apontamento_Disp_Empilhadeira')),
            ],
            options={
                'db_table': 'op_frota_info_os_empilhadeiras',
                'managed': True,
            },
        ),
    ]
