# Generated by Django 3.0.5 on 2024-08-30 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frota_disponibilidade_empilhadeira_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apontamento_disp_empilhadeira',
            table='ger_frota_indisp_frota_apontamento_empilhadeiras',
        ),
        migrations.AlterModelTable(
            name='os_apontamento_disp_empilhadeira',
            table='ger_frota_infor_os_empilhadeiras',
        ),
    ]
