# Generated by Django 3.0.5 on 2024-01-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gabarito_Operacional_Emp',
            fields=[
                ('cod_item_check', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('santos_deep_ogmo', models.IntegerField()),
                ('cod_modelo_empilhadeira', models.IntegerField()),
                ('cod_avaliador', models.IntegerField()),
            ],
            options={
                'db_table': 'op_safe_gab_op_emp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modelo_Emp',
            fields=[
                ('cod_modelo_emp', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_emp', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'op_safe_modelo_emp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Operacao_Emp',
            fields=[
                ('cod_tipo_operacao_emp', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_tipo_operacao_desc', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'op_safe_tipo_operacao',
                'managed': True,
            },
        ),
    ]
