# Generated by Django 3.0.5 on 2024-02-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phishing',
            fields=[
                ('cod_envio', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=70)),
                ('senha', models.CharField(max_length=70)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'op_phishing',
                'managed': True,
            },
        ),
    ]
