# Generated by Django 3.0.5 on 2024-09-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phishing_Enviados',
            fields=[
                ('cod_envio_email', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'op_phishing_enviados',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='phishing',
            name='email',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phishing',
            name='senha',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='phishing',
            name='usuario',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterModelTable(
            name='phishing',
            table='op_phishing_respondidos',
        ),
    ]
