# Generated by Django 3.0.5 on 2023-08-09 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estrut_org_app', '0001_initial'),
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cod_usu', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome_usu', models.TextField(max_length=50, null=True)),
                ('status_usu', models.TextField(default='A', max_length=1)),
                ('data_desativacao', models.DateField(null=True)),
                ('email_usu', models.TextField(max_length=100, null=True)),
                ('perfil_usu', models.TextField(max_length=30)),
                ('login_usu', models.TextField(max_length=50)),
                ('sala', models.CharField(max_length=3, null=True)),
                ('corporativo', models.TextField(default='N', max_length=1)),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proj_Usu',
            fields=[
                ('cod_proj_usu', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_fim_proj_usu', models.DateField(null=True)),
                ('status_proj_usu', models.CharField(default='S', max_length=1)),
                ('cod_projeto', models.ForeignKey(db_column='cod_projeto', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Projeto')),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_proj_usu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usu_Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_usu_menu', models.CharField(default='A', max_length=1)),
                ('cod_menu', models.ForeignKey(db_column='cod_menu', on_delete=django.db.models.deletion.DO_NOTHING, to='menu_app.Menu')),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_usu_menu',
                'managed': True,
                'unique_together': {('cod_usu', 'cod_menu')},
            },
        ),
    ]
