# Generated by Django 3.0.5 on 2023-09-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liberacao_Usuario_Projeto_Benner',
            fields=[
                ('cod_libera_usu_proj', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('handle_benner', models.IntegerField()),
                ('desc_proj_benner', models.CharField(max_length=80)),
                ('ativo_app_folha_pagamento', models.CharField(default='S', max_length=1)),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_liberacao_usu_proj_benner',
                'managed': True,
            },
        ),
    ]
