# Generated by Django 3.0.5 on 2023-11-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0002_liberacao_usuario_projeto_benner'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proj_usu',
            table='ger_proj_usu',
        ),
        migrations.AlterModelTable(
            name='usu_menu',
            table='ger_usu_menu',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='ger_usuarios',
        ),
    ]
