# Generated by Django 3.0.5 on 2024-07-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0003_auto_20231110_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_colab',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
