# Generated by Django 3.0.5 on 2024-09-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0004_usuario_tipo_colab'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberacao_usuario_projeto_benner',
            name='cod_empresa',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
