# Generated by Django 3.0.5 on 2023-08-09 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_app', '0001_initial'),
        ('estrut_org_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verbas_Erros_de_Pagamentos',
            fields=[
                ('cod_verba', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_verba', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'op_geg_erros_pagamentos_verbas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Erros_de_Pagamento',
            fields=[
                ('cod_erro_pagamento', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('cod_colaborador_senior', models.IntegerField()),
                ('nome_colaborador', models.CharField(max_length=80)),
                ('cod_cargo_senior', models.IntegerField(blank=True, null=True)),
                ('desc_cargo', models.CharField(blank=True, max_length=80, null=True)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('mes_competencia', models.DateField()),
                ('valor_erro', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duvida', models.CharField(max_length=300)),
                ('acao', models.CharField(max_length=300)),
                ('nome_responsavel', models.CharField(max_length=30)),
                ('prazo', models.DateField()),
                ('obs', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.IntegerField()),
                ('status_lancamento', models.CharField(default='S', max_length=1)),
                ('data_lancamento', models.DateField(auto_now_add=True)),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
                ('cod_verba', models.ForeignKey(db_column='cod_verba', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='gente_gestao_erros_pagamento_app.Verbas_Erros_de_Pagamentos')),
            ],
            options={
                'db_table': 'op_geg_erros_pagamentos',
                'managed': True,
            },
        ),
    ]
