# Generated by Django 3.0.5 on 2024-08-30 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gente_gestao_erros_pagamento_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='erros_de_pagamento',
            table='ger_gente_gestao_erro_pagamento',
        ),
        migrations.AlterModelTable(
            name='verbas_erros_de_pagamentos',
            table='ger_gente_gestao_verba',
        ),
    ]
