# Generated by Django 3.0.5 on 2022-11-24 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True


    operations = [
        migrations.CreateModel(
            name='Motivo_Just_Preco_Diesel',
            fields=[
                ('cod_motivo_just_preco_diesel', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_motivo_just_preco_diesel', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'op_suprimentos_motivo_just_preco_diesel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Justificativa_Preco_Diesel',
            fields=[
                ('cod_just_preco_diesel', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('handle_itens_compra', models.IntegerField()),
                ('num_compra', models.CharField(max_length=20)),
                ('data_compra', models.DateField()),
                ('val_unit_compra', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_compra_ant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('handle_filial', models.IntegerField()),
                ('nome_filial', models.CharField(max_length=50)),
                ('data_justificativa', models.DateField(auto_now_add=True)),
                ('desc_justificativa', models.CharField(max_length=300)),
                ('cod_motivo_just_preco_diesel', models.ForeignKey(blank=True, db_column='cod_motivo_just_preco_diesel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='suprimentos_justifica_preco_diesel_app.Motivo_Just_Preco_Diesel')),
                ('cod_usu', models.ForeignKey(blank=True, db_column='cod_usu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_suprimentos_justificativa_preco_diesel',
                'managed': True,
            },
        ),
    ]
