"""
Django settings for proj_portal_operacional project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VERSAO_SAFETY = '1.5'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = str(os.getenv('SECRET_KEY'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#Adicionar estes IP's no servidor que hospedar a aplicacao : ALLOWED_HOSTS = ['172.16.40.29', '127.0.0.1', '201.55.114.18', 'operacional.conlogsa.com.br']
ALLOWED_HOSTS = ['172.16.40.29', '127.0.0.1', '201.55.114.18', 'operacional.conlogsa.com.br']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_python3_ldap',
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'channels',
    'channels_redis',
    'apps.home_app',
    'apps.benner_app',
    'apps.conecta_senior_app',
    'apps.estrut_org_app',
    'apps.usuario_app',
    'apps.menu_app',
    'apps.calendario_app',
    'apps.frota_importa_2art_app',
    'apps.plan_controle_fat_2art_terc_app',
    'apps.contabil_composicao_app',
    'apps.gente_gestao_erros_pagamento_app',
    'apps.gente_gestao_fluxo_punitivo',
    'apps.gente_gestao_rem_var_app',
    'apps.frota_disponibilidade_app',
    'apps.suprimentos_tma_app',
    'apps.suprimentos_rel_filial_comprador_app',
    'apps.suprimentos_evolucao_precos_app',
    'apps.plan_controle_folha_pag_analitico_app',
    'apps.plan_controle_provisoes_folha_app',
    'apps.frota_disponibilidade_empilhadeira_app',
    'apps.cco_sinistro_app',
    'apps.seguranca_5s_app',
    'apps.suprimentos_justifica_preco_diesel_app',
    'apps.frota_vpo_app',
    'apps.contabil_operacoes_farol_ndd_app',
    'apps.ti_tma_app',
    'apps.safety_layout_checklist_app',
    'apps.bi_app',
    'apps.cco_multas_app',
    'apps.safety_checks_aplicados_app',
    'apps.safety_gab_op_emp_app',
    'apps.phishing_app',
    'apps.safety_relatos_app',
    'apps.ndd_web_app',
    'apps.gente_gestao_rateio_unimed_app',
    'apps.safety_login_colaboradores_app',
    'apps.frota_vendas_veic_app',
    'apps.dre_app',
    'apps.ti_comitec_app',
    'apps.conecta_rota_app',
    'apps.conecta_as_app',
    'apps.conecta_vans_app',
    'apps.conecta_rv_app',
    'apps.safety_gsdpq_app',
    'apps.safety_blitz_trajeto_carro_app',
    'apps.safety_blitz_trajeto_moto_app',
    'apps.safety_blitz_trajeto_bicicleta_app',
    'apps.safety_blitz_trajeto_outros_meios_app',
    'apps.safety_gso_app',
    'apps.frota_custos_placa_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proj_portal_operacional.urls'



'''
Adicionar este bloco no .29
'''

SETTINGS_PATH = os.path.normpath(os.path.dirname(__file__))
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(SETTINGS_PATH, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

'''TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]'''

WSGI_APPLICATION = 'proj_portal_operacional.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

#Dados para informar em ambiente de produção
'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'portal_operacional',      
        'HOST': '192.168.233.242',
        'USER': 'root',
        'PASSWORD': 'teste678',
        'PORT': '3306',
    }
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'portal_operacional',      
        'HOST': '172.16.40.70',
        'USER': 'servico.python',
        'PASSWORD': 'qm@WHpAWwb',        
        'PORT': '3306',
    }
}

'''


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': str(os.getenv('NOME_BANCO')),
        'HOST': str(os.getenv('IP_BANCO')),
        'USER': str(os.getenv('USER')),
        'PASSWORD': str(os.getenv('PASS')),
        'PORT': '3306',
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

CRISPY_TEMPLATE_PACK = 'bootstrap4'

ASGI_APPLICATION = 'proj_portal_operacional.routing.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379),],
        }
    }
}

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django_plotly_dash.finders.DashAssetFinder',
    'django_plotly_dash.finders.DashComponentFinder'
]

PLOTLY_COMPONENTS = [
    'dash_core_components',
    'dash_html_components',
    'dash_renderer',

    'dpd_components'
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]



DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240

FILE_UPLOAD_MAX_MEMORY_SIZE = 600000000



TEMPLATE_DEBUG = True
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')




X_FRAME_OPTIONS = 'SAMEORIGIN'
QUESTION_FILE_FORMAT = ['.jpg', '.pdf', '.txt', '.xlsx']
XS_SHARING_ALLOWED_METHODS = ['POST','GET','OPTIONS', 'PUT', 'DELETE']


#Active Directory
LDAP_AUTH_URL = 'ldap://172.16.40.2' #192.168.22.2
LDAP_AUTH_USE_TLS = False
LDAP_AUTH_SEARCH_BASE = 'ou=Usuarios,ou=CONLOG,dc=conlog,dc=local'
LDAP_AUTH_OBJECT_CLASS = 'Usuario'
LDAP_AUTH_USER_FIELDS = {
    "nome_usu": "name",
    "login_usu" : "sAMAccountName",
    "senha_usu" : "physicalDeliveryOfficeName",
    "email": "mail",
}
LDAP_AUTH_USER_LOOKUP_FIELDS = ('username',)
LDAP_AUTH_CLEAN_USER_DATA = 'django_python3_ldap.utils.clean_user_data'
LDAP_AUTH_SYNC_USER_RELATIONS = 'django_python3_ldap.utils.sync_user_relations'
LDAP_AUTH_FORMAT_SEARCH_FILTERS = 'django_python3_ldap.utils.format_search_filters'
LDAP_AUTH_FORMAT_USERNAME = 'django_python3_ldap.utils.format_username_active_directory'
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = 'conlog.local'
LDAP_AUTH_CONNECTION_USERNAME = 'Administrador'
LDAP_AUTH_CONNECTION_PASSWORD = 'Clsa@9856@#'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'django_python3_ldap.auth.LDAPBackend',
)

#Constatne para configurar envio de email
EMAIL_HOST = 'webmail.conlogsa.com.br'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'danilo.costa@conlogsa.com.br'
EMAIL_HOST_PASSWORD = 'dap@1104!'
EMAIL_USE_TLS = False


X_FRAME_OPTIONS  = 'SAMEORIGIN'