
# Generated by Django 3.0.5 on 2024-09-05 18:09

# Generated by Django 3.0.5 on 2024-08-30 17:57


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [

        ('estrut_org_app', '0004_filial_tem_calculo_rv'),
        ('usuario_app', '0005_liberacao_usuario_projeto_benner_cod_empresa'),

        ('usuario_app', '0005_liberacao_usuario_projeto_benner_cod_empresa'),
        ('estrut_org_app', '0004_filial_tem_calculo_rv'),

    ]

    operations = [
        migrations.CreateModel(
            name='CCO_Sinistro',
            fields=[
                ('cod_sinistro', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome_mot', models.CharField(max_length=80)),
                ('status_processo', models.CharField(max_length=20)),
                ('data_inclusao', models.DateField(max_length=15)),
                ('cpf_mot', models.CharField(blank=True, max_length=11, null=True)),
                ('placa_veiculo_cavalo', models.CharField(max_length=12)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('data_ocorre_sinistro', models.DateField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=30, null=True)),
                ('acionado_seguro', models.CharField(blank=True, default='S', max_length=3, null=True)),
                ('data_inicio_processo', models.DateField(blank=True, null=True)),
                ('data_fim_processo', models.DateField(blank=True, null=True)),
                ('num_processo', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo_sinistro', models.CharField(blank=True, max_length=20, null=True)),
                ('obs', models.CharField(blank=True, max_length=500, null=True)),
                ('cod_estado', models.ForeignKey(blank=True, db_column='cod_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.OP_Estados')),
            ],
            options={
                'db_table': 'ger_cco_sinistros',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Motivo_Sinistro',
            fields=[
                ('cod_motivo_sinistro', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_motivo_sinistro', models.CharField(max_length=50)),
                ('tipo_motivo_sinistro', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'ger_cco_motivos_sinistros',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CCO_Sinistro_Equipamento',
            fields=[
                ('cod_sinistro_equipamento', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_comunicacao_seguradora', models.DateField(blank=True, null=True)),
                ('data_comunicacao_cco', models.DateField(blank=True, null=True)),
                ('resp_dano', models.CharField(blank=True, max_length=30, null=True)),
                ('descontado_colab', models.CharField(default='S', max_length=5, null=True)),
                ('indenizado', models.CharField(blank=True, default='S', max_length=3, null=True)),
                ('houve_danos_emp', models.CharField(blank=True, default='S', max_length=1, null=True)),
                ('val_indenizado', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('val_prejuizo', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('resp_indenizar_dano', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_acionamento', models.CharField(blank=True, max_length=30, null=True)),
                ('feito_reembolso_eqp', models.CharField(blank=True, max_length=3, null=True)),
                ('cod_sinistro', models.ForeignKey(db_column='cod_sinistro', on_delete=django.db.models.deletion.CASCADE, to='cco_sinistro_app.CCO_Sinistro')),
            ],
            options={
                'db_table': 'ger_cco_sinistros_equipamentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CCO_Sinistro_Carga',
            fields=[
                ('cod_sinistro_carga', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=20)),
                ('tipo_frota', models.CharField(max_length=10)),
                ('transportador', models.CharField(max_length=10)),
                ('placa_veiculo_carreta', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_veiculo', models.CharField(max_length=12)),
                ('cliente', models.CharField(max_length=10)),
                ('tipo_mercadoria', models.CharField(max_length=12)),
                ('num_nota_fiscal', models.CharField(blank=True, max_length=6, null=True)),
                ('cte_serie', models.CharField(blank=True, max_length=10, null=True)),
                ('valor_tot_produtos', models.CharField(blank=True, max_length=12, null=True)),
                ('hora_sinistro', models.TimeField(blank=True, null=True)),
                ('local_ocorre_sinistro', models.CharField(blank=True, max_length=30, null=True)),
                ('valor_sinistro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resp_seguro', models.CharField(blank=True, max_length=200, null=True)),
                ('seguradora', models.CharField(blank=True, max_length=20, null=True)),
                ('reguladora', models.CharField(blank=True, max_length=30, null=True)),
                ('reembolso', models.CharField(blank=True, default='S', max_length=1, null=True)),
                ('val_reembolso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_abertura_registro_sinistro', models.DateField(blank=True, null=True)),
                ('data_fechamento_registro_sinistro', models.DateField(blank=True, null=True)),
                ('status_doc', models.CharField(blank=True, max_length=20)),
                ('cod_sinistro', models.ForeignKey(db_column='cod_sinistro', on_delete=django.db.models.deletion.CASCADE, to='cco_sinistro_app.CCO_Sinistro')),
            ],
            options={
                'db_table': 'ger_cco_sinistros_cargas',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cco_sinistro',
            name='cod_motivo_sinistro',
            field=models.ForeignKey(db_column='cod_motivo_sinistro', on_delete=django.db.models.deletion.DO_NOTHING, to='cco_sinistro_app.Motivo_Sinistro'),
        ),
        migrations.AddField(
            model_name='cco_sinistro',
            name='cod_projeto',
            field=models.ForeignKey(blank=True, db_column='cod_projeto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Projeto'),
        ),
        migrations.AddField(
            model_name='cco_sinistro',
            name='cod_usu',
            field=models.ForeignKey(blank=True, db_column='cod_usu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario'),
        ),
    ]
