# Generated by Django 3.0.5 on 2024-09-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('cod_colaborador', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('matricula_colaborador', models.IntegerField(blank=True, null=True)),
                ('nome_colaborador', models.CharField(max_length=100)),
                ('cod_filial', models.IntegerField()),
                ('desc_cargo', models.CharField(blank=True, max_length=80, null=True)),
                ('cnh', models.CharField(blank=True, max_length=20, null=True)),
                ('validade_cnh', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('perfil_usu', models.CharField(max_length=1)),
                ('setor', models.IntegerField(blank=True, null=True)),
                ('situacao', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'op_safe_colaboradores',
                'managed': True,
            },
        ),
    ]
