# Generated by Django 3.0.5 on 2023-08-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('cod_menu', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_menu', models.CharField(max_length=40)),
                ('status_menu', models.CharField(default='A', max_length=1)),
                ('pai_menu', models.IntegerField(default=0)),
                ('nome_icone', models.CharField(max_length=200, null=True)),
                ('url_menu', models.CharField(default=0, max_length=150)),
            ],
            options={
                'db_table': 'op_menus',
                'managed': True,
            },
        ),
    ]
