# Generated by Django 3.0.5 on 2023-08-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='desc_menu',
            field=models.CharField(max_length=50),
        ),
    ]
