# Generated by Django 3.0.5 on 2024-09-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_auto_20230809_0013'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='ger_menus',
        ),
    ]
