# Generated by Django 3.0.5 on 2023-08-17 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estrut_org_app', '0001_initial'),
        ('usuario_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacao_Filial_Comprador',
            fields=[
                ('cod_rel_filial_comprador', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_ini', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_suprimentos_relacao_filial_comprador',
                'managed': True,
            },
        ),
    ]
