# Generated by Django 3.0.5 on 2024-08-30 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos_rel_filial_comprador_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='relacao_filial_comprador',
            table='ger_suprimentos_relacao_filial_comprador',
        ),
    ]
