# Generated by Django 3.0.5 on 2024-09-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Cluster',
            fields=[
                ('cod_item_cluster', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_item_cluster', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'op_frota_custos_itens_cluster',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Razao_Frota',
            fields=[
                ('cod_razao_frota', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('handle_lanc', models.IntegerField()),
                ('placa', models.CharField(max_length=10)),
                ('handle_projeto', models.IntegerField()),
                ('desc_projeto', models.CharField(max_length=80)),
                ('desc_tipo_conta', models.CharField(max_length=60)),
                ('doc_contabil', models.CharField(blank=True, max_length=30, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('historico', models.CharField(blank=True, max_length=500, null=True)),
                ('nome_fornecedor', models.CharField(blank=True, max_length=80, null=True)),
                ('codigo_os', models.CharField(blank=True, max_length=60, null=True)),
                ('desc_os', models.CharField(blank=True, max_length=500, null=True)),
                ('desc_tipo_os', models.CharField(blank=True, max_length=80, null=True)),
                ('obs_os', models.CharField(blank=True, max_length=500, null=True)),
                ('itens_os', models.CharField(blank=True, max_length=500, null=True)),
                ('cod_item_cluster', models.ForeignKey(blank=True, db_column='cod_item_cluster', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frota_custos_placa_app.Item_Cluster')),
            ],
            options={
                'db_table': 'op_frota_custos_razao_cluster',
                'managed': True,
            },
        ),
    ]
