from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from apps.contabil_composicao_app import views_dic, views

urlpatterns = [
    path('acessa_form_cadastros_comp', views.Form_Imp_Cad_Conta_View.as_view(),
         name='acessa_form_cadastros_comp'),
    #path('retorna_dados_conta_cadastrada', views.Comp_CB_Contas_Benner_View.as_view(),
    #    name='retorna_dados_conta_cadastrada'),
    path('retorna_dados_conta_cadastrada', views.Form_Cad_Conta_View.as_view(),
         name='retorna_dados_conta_cadastrada'),
    path('retorna_dados_contrato_conta_cadastrada', views.Form_Cad_Contrato_View.as_view(),
         name='retorna_dados_contrato_conta_cadastrada'),
    path('acessa_frm_cad_contratos', views.Form_Cad_Contrato_View.as_view(),
         name='acessa_frm_cad_contratos'),
    path('retorna_dados_contrato_benner_conta', views.Form_Imp_Contratos_Conta_View.as_view(),
         name='retorna_dados_contrato_benner_conta'),
    path('cria_atualiza_conta', views.Form_Cad_Conta_View.as_view(),
         name='cria_atualiza_conta'),
    path('cadastro_contrato', views.Form_Cad_Contrato_View.as_view(),
         name='cadastro_contrato'),
    path('associa_resp_conta', views.Form_Associa_Resp_Conta_View.as_view(),
         name='associa_resp_conta'),
    path('retorna_resp_associados_conta', views.Form_Associa_Resp_Conta_View.as_view(),
         name='retorna_resp_associados_conta'),
    path('atualiza_status_contrato_sincroniza_benner', views.Form_Cad_Contrato_View.as_view(),
         name='atualiza_status_contrato_sincroniza_benner'),
    path('atualiza_dados_parcela', views.Form_Cad_Parcelas_Contrato_View.as_view(),
         name='atualiza_dados_parcela'),
    path('estornar_parc_ctr_contas_m3/<str:pk>/', views.Form_Cad_Parcelas_Contrato_View.as_view(),
         name='estornar_parc_ctr_contas_m3'),
    path('acessa_form_conciliacao_composicao_benner_resumo', views.Form_Conciliacao_Comp_Benner_Resumo_View.as_view(),
         name='acessa_form_conciliacao_composicao_benner_resumo'),
    path('acessa_form_conciliacao_composicao_benner_detalhado', views.Form_Conciliacao_Comp_Benner_Detalhado_View.as_view(),
         name='acessa_form_conciliacao_composicao_benner_detalhado'),
    path('registra_status_composicao_conta', views.Form_Conciliacao_Comp_Benner_Detalhado_View.as_view(),
         name='registra_status_composicao_conta'),
    path('povoa_cb_contas_conciliacao_comp_benner', views.Comp_Cb_Contas_Conciliacao_Comp_Benner_View.as_view(),
         name='povoa_cb_contas_conciliacao_comp_benner'),
    path('gera_conciliacao_comp_benner', views.Gera_Conciliacao_Comp_Benner_View.as_view(),
         name='gera_conciliacao_comp_benner'),
    path('salva_caminho_anexo_conta', views.Form_Anexos_Conta_View.as_view(),
         name='salva_caminho_anexo_conta'),
    path('retorna_lista_anexos_conta', views.Form_Anexos_Conta_View.as_view(),
         name='retorna_lista_anexos_conta'),
    path('exclui_anexo_conta/<int:pk>/', views.Form_Anexos_Conta_View.as_view(),
         name='exclui_anexo_conta'),
    path('exclui_contrato/<int:pk>/', views.Form_Cad_Contrato_View.as_view(),
         name='exclui_contrato'),
    path('retorna_lista_status_contrato_composicao', views.Form_Status_Contrato_Composicao_View.as_view(),
         name='retorna_lista_status_contrato_composicao'),
    path('excluir_aud_comp/<int:pk>/', views.Form_Status_Contrato_Composicao_View.as_view(),
         name='excluir_aud_comp'),
    path('visualiza_doc_contrato_competencia', views.Form_Visualiza_Doc_Contrato_View.as_view(),
         name='visualiza_doc_contrato_competencia'),
    path('acessa_form_doc_contas_modelo_1', views.Tabela_Pac_Contas_Modelo_1_View.as_view(),
         name='acessa_form_doc_contas_modelo_1'),
    path('acessa_form_importa_arq_contas_modelo_1', views.Form_Imp_Arq_Contas_M1_View.as_view(),
         name='acessa_form_importa_arq_contas_modelo_1'),
    path('importa_arqv_contas_m1', views.Form_Imp_Arq_Contas_M1_View.as_view(),
         name='importa_arqv_contas_m1'),
    path('pesq_dados_importado_contas_m1', views.Form_Pesq_Arq_Contas_M1_View.as_view(),
         name='pesq_dados_importado_contas_m1'),
    path('retorna_lista_docs_contas_modelo_1', views.Tabela_Doc_Contas_Modelo_1_View.as_view(),
         name='retorna_lista_docs_contas_modelo_1'),
    path('exclui_arquivo_conta_m_1/<str:pk>/', views.Tabela_Doc_Contas_Modelo_1_View.as_view(),
         name='exclui_arquivo_conta_m_1'),
    path('acessa_form_auditoria_comp', views.Form_Composicao_Auditoria_View.as_view(),
         name='acessa_form_auditoria_comp'),
    path('acessa_frm_vinc_resp', views.Form_Vincula_Resp_Contas_View.as_view(),
         name='acessa_frm_vinc_resp'),
    path('retorna_contas_responsaveis_selecionados', views.Form_Contas_Resp_View.as_view(),
         name='retorna_contas_responsaveis_selecionados'),
    path('informa_data_fim_resp_conta', views.Form_Contas_Resp_View.as_view(),
         name='informa_data_fim_resp_conta'),
    path('exclui_reg_resp_conta/<int:pk>/', views.Form_Contas_Resp_View.as_view(),
         name='exclui_reg_resp_conta'),
    path('retorna_contas_por_pac_e_regs_resp_contas', views.Form_Vincula_Contas_Resp_View.as_view() ,
         name='retorna_contas_por_pac_e_regs_resp_contas'),
    path('importa_anexo_geral_contas', views.Importa_Anexos_Contas_View.as_view(),
         name='importa_anexo_geral_contas'),
    path('acessa_form_importa_arq_pac_modelo_1', views.Form_Doc_Pac_Modelo_1_View.as_view(),
         name='acessa_form_importa_arq_pac_modelo_1'),
    path('atualiza_contas_cb_contas_pac_doc_m1', views.Comp_Cb_Contas_Imp_Docs_Pac_M1_View.as_view(),
         name='atualiza_contas_cb_contas_pac_doc_m1'),
    path('pesq_dados_importado_pac_contas_m1', views.Form_Pesq_Arq_Pac_Contas_M1_View.as_view(),
         name='pesq_dados_importado_pac_contas_m1'),
    path('atualiza_contratos_com_dados_do_benner', views.Form_Atualiza_Contratos_Benner_View.as_view(),
         name='atualiza_contratos_com_dados_do_benner'),
    path('atualiza_parcelas_data_corte', views.Form_Atualiza_Parcelas_Data_Corte.as_view(),
         name='atualiza_parcelas_data_corte'),
    path('retorna_dados_doc_pac_contas_pag_receb', views.Docs_Pac_Contas_Pagar_Receber_M1_View.as_view(),
         name='altera_dados_doc_pac_contas_pag_receb'),
    path('altera_dados_doc_pac_contas_pag_receb', views.Docs_Pac_Contas_Pagar_Receber_M1_View.as_view(),
         name='altera_dados_doc_pac_contas_pag_receb'),
    path('exclui_doc_pac_pagar_receber/<str:pk>/', views.Docs_Pac_Contas_Pagar_Receber_M1_View.as_view(),
         name='exclui_doc_pac_pagar_receber'),
    path('retorna_dados_doc_pac_estoque', views.Docs_Pac_Estoque_M1_View.as_view(),
         name='retorna_dados_doc_pac_estoque'),
    path('altera_dados_doc_pac_estoque', views.Docs_Pac_Estoque_M1_View.as_view(),
         name='altera_dados_doc_pac_estoque'),
    path('exclui_doc_pac_estoque/<str:pk>/', views.Docs_Pac_Estoque_M1_View.as_view(),
         name='exclui_doc_pac_estoque'),
    path('retorna_dados_doc_pac_folha_pag', views.Docs_Pac_Folha_Pag_M1_View.as_view(),
         name='retorna_dados_doc_pac_folha_pag'),
    path('altera_dados_doc_pac_folha_pag', views.Docs_Pac_Folha_Pag_M1_View.as_view(),
         name='altera_dados_doc_pac_folha_pag'),
    path('exclui_doc_pac_folha_pag/<str:pk>', views.Docs_Pac_Folha_Pag_M1_View.as_view(),
         name='exclui_doc_pac_folha_pag'),
    path('retorna_dados_doc_pac_compensacao', views.Docs_Pac_Contas_Compensacao_M1_View.as_view(),
         name='retorna_dados_doc_pac_compensacao'),
    path('altera_dados_doc_pac_composicao', views.Docs_Pac_Contas_Compensacao_M1_View.as_view(),
         name='altera_dados_doc_pac_composicao'),
    path('exclui_doc_pac_comensacao/<str:pk>', views.Docs_Pac_Contas_Compensacao_M1_View.as_view(),
         name='exclui_doc_pac_comensacao'),
    path('retorna_dados_doc_pac_tributos', views.Docs_Pac_Tributos_M1_View.as_view(),
         name='retorna_dados_doc_pac_tributos'),
    path('altera_dados_doc_pac_trib', views.Docs_Pac_Tributos_M1_View.as_view(),
         name='altera_dados_doc_pac_trib'),
    path('exclui_doc_pac_tributo/<str:pk>', views.Docs_Pac_Tributos_M1_View.as_view(),
         name='exclui_doc_pac_tributo'),
    path('retorna_dados_doc_pac_financ_disp', views.Docs_Pac_Finac_Disponib_M1_View.as_view(),
         name='retorna_dados_doc_pac_financ_disp'),
    path('altera_dados_doc_pac_financ_disp', views.Docs_Pac_Finac_Disponib_M1_View.as_view(),
         name='altera_dados_doc_pac_financ_disp'),
    path('exclui_doc_pac_financ_disp/<str:pk>', views.Docs_Pac_Finac_Disponib_M1_View.as_view(),
         name='exclui_doc_pac_financ_disp'),
    path('retorna_dados_doc_pac_intercompany', views.Docs_Pac_Intercompany_M1_View.as_view(),
         name='retorna_dados_doc_pac_intercompany'),
    path('altera_dados_doc_pac_intercompany', views.Docs_Pac_Intercompany_M1_View.as_view(),
         name='altera_dados_doc_pac_intercompany'),
    path('exclui_doc_pac_intercompany/<str:pk>', views.Docs_Pac_Intercompany_M1_View.as_view(),
         name='exclui_doc_pac_intercompany'),
    path('retorna_dados_doc_pac_imobilizado', views.Docs_Pac_Imobilizado_M1_View.as_view(),
         name='retorna_dados_doc_pac_imobilizado'),
    path('altera_dados_doc_imobilizado', views.Docs_Pac_Imobilizado_M1_View.as_view(),
         name='altera_dados_doc_imobilizado'),
    path('exclui_doc_pac_imobilizado/<str:pk>', views.Docs_Pac_Imobilizado_M1_View.as_view(),
         name='exclui_doc_pac_imobilizado'),
    path('retorna_dados_doc_pac_consorc_atv', views.Docs_Pac_Consorcio_Ativo_M1_View.as_view(),
         name='Docs_Pac_Consorcio_Ativo_M1_View'),
    path('altera_dados_doc_consorc_atv', views.Docs_Pac_Consorcio_Ativo_M1_View.as_view(),
         name='altera_dados_doc_consorc_atv'),
    path('exclui_doc_pac_consorcios_ativos/<str:pk>', views.Docs_Pac_Consorcio_Ativo_M1_View.as_view(),
         name='exclui_doc_pac_consorcios_ativos'),
    path('retorna_dados_doc_pac_demais_contas', views.Docs_Demais_Contas_M1_View.as_view(),
         name='Docs_Demais_Contas_M1_View'),
    path('altera_dados_doc_pac_demais_contas', views.Docs_Demais_Contas_M1_View.as_view(),
         name='Docs_Demais_Contas_M1_View'),
    path('exclui_doc_pac_demais_contas/<str:pk>', views.Docs_Demais_Contas_M1_View.as_view(),
         name='exclui_doc_pac_demais_contas'),
    path('retorna_docs_conta_m1', views.Form_Docs_Conta_M1_View.as_view(),
         name='retorna_docs_conta_m1'),
    path('acessa_frm_detalhes_conta_composicao', views.Form_Detalhes_Conta_Composicao_View.as_view(),
         name='acessa_frm_detalhes_conta_composicao'),
    path('povoa_cb_pac_contas_comp_detalhado', views.Comp_Pac_Contas_Comp_Detalhado_View.as_view(),
         name='povoa_cb_pac_contas_comp_detalhado'),
    path('renegociar_contrato', views.Form_Renegociacao_Contrato_View.as_view(),
         name='renegociar_contrato'),
    path('altera_status_anexo_conta_ver_na_composicao', views.Form_Visualiza_Doc_Contrato_View.as_view(),
         name='altera_status_anexo_conta_ver_na_composicao'),
    path('atualiza_cb_contas_responsaveis_contas', views.Comp_Contas_Resp_View.as_view(),
         name='atualiza_cb_contas_responsaveis_contas'),
    path('desativa_resp_contas_em_lote', views.Form_Vincula_Resp_Contas_View.as_view(),
         name='desativa_resp_contas_em_lote'),
    path('povoa_tabela_status_proc_contabil', views.Form_Status_Proc_Contabil_View.as_view(),
         name='povoa_tabela_status_proc_contabil'),
    path('adiciona_novo_status_processo_contabil', views.Form_Status_Proc_Contabil_View.as_view(),
         name='adiciona_novo_status_processo_contabil'),
    path('atualiza_data_fim_status_proc_contabil', views.Form_Status_Proc_Contabil_View.as_view(),
         name='atualiza_data_fim_status_proc_contabil'),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)