from django.db import models

from apps.estrut_org_app.models import Projeto
from apps.usuario_app.models import Usuario


class IndicaProjReg2Art(models.Model):
    cod_reg_indc_cod_reg_2art = models.AutoField(primary_key=True, editable=False, blank=False, auto_created=True)
    cod_projeto = models.ForeignKey(Projeto, models.DO_NOTHING, db_column='cod_projeto')
    cod_filial_promax = models.CharField(max_length=5, null=True)
    tipo_entrega = models.CharField(max_length=10, null=True)
    tipo_frota = models.CharField(max_length=15, null=True)
    class Meta:
        managed = True
        db_table = 'ger_indica_cod_proj_reg_2art'#op_frota_indica_cod_proj_reg_2art'


class Arquivo2Art(models.Model):
    cod_reg_arq_imp = models.AutoField(primary_key=True, editable=False, blank=False, auto_created=True)
    data_arq_imp = models.DateField(auto_now_add=True)
    hora_arq_imp = models.TimeField(auto_now_add=True)
    nome_arq_original = models.CharField(max_length=500, null=True)
    nome_arq_imp = models.CharField(max_length=500, null=True)
    qtd_registros = models.IntegerField()
    qtd_importados = models.IntegerField()
    qtd_atualizados = models.IntegerField()
    cod_usu = models.ForeignKey(Usuario, models.DO_NOTHING, db_column='cod_usu')
    class Meta:
        managed = True
        db_table = 'ger_arq_2art'


class Registro2Art(models.Model):
    cod_reg_2art = models.IntegerField(primary_key=True)
    data = models.DateField(null=True)
    transp = models.CharField(max_length=2,null=True)
    entrega = models.CharField(max_length=20,null=True)
    cargaatual = models.CharField(max_length=20,null=True)
    frota = models.CharField(max_length=20,null=True)
    custospot = models.CharField(max_length=20,null=True)
    regiaospot = models.CharField(max_length=5,null=True)
    veiculo = models.CharField(max_length=10,null=True)
    placa = models.CharField(max_length=10,null=True)
    veiculoindisp = models.CharField(max_length=5,null=True)
    placaindisp = models.CharField(max_length=10,null=True)
    frotaindisp = models.CharField(max_length=20,null=True)
    tipoindisp = models.CharField(max_length=5,null=True)
    mapa = models.CharField(max_length=10,null=True)
    entregas = models.CharField(max_length=5,null=True)
    cxcarreg = models.CharField(max_length=10,null=True)
    cxentreg = models.CharField(max_length=10, null=True)
    ocupacao = models.CharField(max_length=10,null=True)
    cxrota = models.CharField(max_length=5,null=True)
    cxas = models.CharField(max_length=5,null=True)
    veicbm = models.CharField(max_length=10,null=True)
    rshow = models.CharField(max_length=10,null=True)
    entrvol = models.CharField(max_length=20,null=True)
    hrsai = models.CharField(max_length=25,null=True)
    hrentr = models.CharField(max_length=25,null=True)
    kmsai = models.CharField(max_length=20,null=True)
    kmentr = models.CharField(max_length=20,null=True)
    custovariavel = models.CharField(max_length=20,null=True)
    lucro = models.CharField(max_length=10,null=True)
    lucrounit = models.CharField(max_length=10,null=True)
    valorfrete = models.CharField(max_length=10,null=True)
    tipoimposto = models.CharField(max_length=25,null=True)
    percimposto = models.CharField(max_length=10,null=True)
    valorimposto = models.CharField(max_length=10,null=True)
    valorfaturado = models.CharField(max_length=10,null=True)
    valorunitcxentregue = models.CharField(max_length=10,null=True)
    valorpgcxentregsemimp = models.CharField(max_length=10,null=True)
    valorpgcxentregcomimp = models.CharField(max_length=10,null=True)
    tempoprevistoroad = models.CharField(max_length=10,null=True)
    kmprevistoroad = models.CharField(max_length=20,null=True)
    valorunitpontomot =models.CharField(max_length=10,null=True)
    valorunitpontoajd = models.CharField(max_length=10,null=True)
    valorequipeentrmot = models.CharField(max_length=10,null=True)
    valorequipeentrajd = models.CharField(max_length=10,null=True)
    custovlc = models.CharField(max_length=10,null=True)
    lucrounitcedbz = models.CharField(max_length=10,null=True)
    custovlccxentr = models.CharField(max_length=10,null=True)
    tempointerno = models.CharField(max_length=20,null=True)
    valordropdown = models.CharField(max_length=10,null=True)
    veiccaddd = models.CharField(max_length=5,null=True)
    kmlaco = models.CharField(max_length=10,null=True)
    kmdeslocamento = models.CharField(max_length=10,null=True)
    tempolaco = models.CharField(max_length=10,null=True)
    tempodeslocamento = models.CharField(max_length=10,null=True)
    sitmulticdd = models.CharField(max_length=10,null=True)
    unborigem = models.CharField(max_length=10,null=True)
    matricmotorista = models.CharField(max_length=10,null=True)
    matricajud1 = models.CharField(max_length=10,null=True)
    matricajud2 = models.CharField(max_length=10,null=True)
    valorctedifere = models.CharField(max_length=10,null=True)
    qtnfcarregadas = models.CharField(max_length=10,null=True)
    qtnfentregues = models.CharField(max_length=10,null=True)
    inddevcx = models.CharField(max_length=10,null=True)
    inddevnf = models.CharField(max_length=10,null=True)
    fator = models.CharField(max_length=5,null=True)
    recarga = models.CharField(max_length=5,null=True)
    hrmatinal = models.CharField(max_length=25,null=True)
    hrjornadaliq = models.CharField(max_length=25,null=True)
    hrmetajornada = models.CharField(max_length=25,null=True)
    vlbateujornmot = models.CharField(max_length=10,null=True)
    vlnaobateujornmot = models.CharField(max_length=10,null=True)
    vlrecargamot = models.CharField(max_length=10,null=True)
    vlbateujornaju = models.CharField(max_length=10,null=True)
    vlnaobateujornaju = models.CharField(max_length=10,null=True)
    vlrecargaaju = models.CharField(max_length=10,null=True)
    vltotalmapa = models.CharField(max_length=10,null=True)
    qthlcarregados = models.CharField(max_length=20,null=True)
    qthlentregues = models.CharField(max_length=20,null=True)
    indicedevhl = models.CharField(max_length=10,null=True)
    regiao = models.CharField(max_length=20,null=True)
    qtnfcarreggeral = models.CharField(max_length=10,null=True)
    qtnfentreggeral = models.CharField(max_length=10,null=True)
    capacidadeveiculokg = models.CharField(max_length=10,null=True)
    pesocargakg = models.CharField(max_length=20,null=True)
    capacveiculocx = models.CharField(max_length=15,null=True)
    entregascompletas = models.CharField(max_length=5,null=True)
    entregasparciais = models.CharField(max_length=5,null=True)
    entregasnaorealizadas = models.CharField(max_length=5,null=True)
    codfilial = models.CharField(max_length=10,null=True)
    nomefilial = models.CharField(max_length=50,null=True)
    codsupervtrs = models.CharField(max_length=10,null=True)
    nomesupervtrs = models.CharField(max_length=50,null=True)
    codspot = models.CharField(max_length=10,null=True)
    nomespot = models.CharField(max_length=30,null=True)
    equipcarregados = models.CharField(max_length=10,null=True)
    equipdevolvidos = models.CharField(max_length=10,null=True)
    equiprecolhidos = models.CharField(max_length=10,null=True)
    cxentregtracking = models.CharField(max_length=10,null=True)
    hrcarreg = models.CharField(max_length=25,null=True)
    hrpcfisica = models.CharField(max_length=25,null=True)
    hrpcfinanceira = models.CharField(max_length=25,null=True)
    stmapa = models.CharField(max_length=20,null=True)
    qtentregascarregrv = models.CharField(max_length=5,null=True)
    qtentregasentregrv = models.CharField(max_length=5,null=True)
    indicedeventregasrv = models.CharField(max_length=15,null=True)
    cpfmotorista = models.CharField(max_length=15,null=True)
    cpfajudante1 = models.CharField(max_length=15,null=True)
    cpfajudante2 = models.CharField(max_length=15,null=True)
    alterado = models.CharField(max_length=1,null=True)
    acao = models.CharField(max_length=1,null=True)
    cod_reg_indc_cod_reg_2art = models.ForeignKey(IndicaProjReg2Art, models.DO_NOTHING, db_column='cod_reg_indc_cod_reg_2art')
    cod_reg_arq_imp = models.ForeignKey(Arquivo2Art, models.DO_NOTHING, db_column='cod_reg_arq_imp')
    class Meta:
        managed = True
        db_table = 'ger_2art'#op_frota_2art'

