# Generated by Django 3.0.5 on 2023-09-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frota_importa_2art_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='arquivo2art',
            table='ger_arq_2art',
        ),
        migrations.AlterModelTable(
            name='indicaprojreg2art',
            table='ger_indica_cod_proj_reg_2art',
        ),
        migrations.AlterModelTable(
            name='registro2art',
            table='ger_2art',
        ),
    ]
