# Generated by Django 3.0.5 on 2023-08-09 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_app', '0001_initial'),
        ('estrut_org_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('cod_conta', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('handle_conta_contabil_cp', models.IntegerField()),
                ('cod_red_conta_contabil_cp', models.IntegerField()),
                ('handle_conta_financeira_cp', models.IntegerField(blank=True, null=True)),
                ('cod_estrut_cp', models.CharField(blank=True, max_length=30, null=True)),
                ('handle_conta_contabil_lp', models.IntegerField()),
                ('cod_red_conta_contabil_lp', models.IntegerField()),
                ('handle_conta_financeira_lp', models.IntegerField(blank=True, null=True)),
                ('cod_estrut_lp', models.CharField(blank=True, max_length=30, null=True)),
                ('desc_conta', models.CharField(max_length=80)),
                ('tipo_modelo', models.IntegerField()),
                ('data_ini_atividade', models.DateTimeField(blank=True, null=True)),
                ('data_fim_atividade', models.DateTimeField(blank=True, null=True)),
                ('status_comp', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'op_contabil_comp_contas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('cod_contrato', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('handle_fn_doc', models.IntegerField()),
                ('num_contrato', models.CharField(max_length=45)),
                ('data_emissao_contrato', models.DateTimeField(blank=True, null=True)),
                ('nome_fornecedor', models.CharField(blank=True, max_length=150, null=True)),
                ('handle_operacao', models.IntegerField(blank=True, null=True)),
                ('desc_op', models.CharField(blank=True, max_length=60, null=True)),
                ('num_doc_contabil', models.CharField(blank=True, max_length=45, null=True)),
                ('val_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('val_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sincronizar_benner', models.CharField(blank=True, default='S', max_length=1, null=True)),
                ('dia_util', models.IntegerField(blank=True, null=True)),
                ('data_primeira_parcela', models.DateTimeField(blank=True, null=True)),
                ('qtd_parcelas', models.IntegerField(blank=True, null=True)),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_empresa', models.ForeignKey(db_column='cod_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Empresa')),
            ],
            options={
                'db_table': 'op_contabil_comp_contratos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pacote_Conta',
            fields=[
                ('cod_pacote_conta', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_pacote_conta', models.CharField(max_length=30)),
                ('obs_pacotes', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'op_contabil_comp_pac_conta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Responsaveis_Conta',
            fields=[
                ('cod_resp_conta', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('resp_composicao', models.CharField(blank=True, max_length=60, null=True)),
                ('resp_validacao', models.CharField(blank=True, max_length=60, null=True)),
                ('data_ini_atividade', models.DateTimeField(blank=True, null=True)),
                ('data_fim_atividade', models.DateTimeField(blank=True, null=True)),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_empresa', models.ForeignKey(db_column='cod_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Empresa')),
            ],
            options={
                'db_table': 'op_contabil_resp_conta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parcela_Contrato',
            fields=[
                ('cod_parcela_contrato', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('handle_parcela', models.IntegerField(blank=True, null=True)),
                ('ap_parcela', models.IntegerField(blank=True, null=True)),
                ('ordem_parcela', models.CharField(max_length=10)),
                ('val_conta', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('val_corrigido', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('val_principal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('val_taxas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('natureza', models.CharField(blank=True, max_length=1, null=True)),
                ('data_vencimento', models.DateTimeField(blank=True, null=True)),
                ('tipo_prazo', models.CharField(blank=True, max_length=2, null=True)),
                ('data_liquidacao', models.DateTimeField(blank=True, null=True)),
                ('atualiza_benner', models.CharField(max_length=1)),
                ('val_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cod_contrato', models.ForeignKey(db_column='cod_contrato', on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Contrato')),
            ],
            options={
                'db_table': 'op_contabil_comp_parcelas_contratos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='conta',
            name='cod_pacote_conta',
            field=models.ForeignKey(blank=True, db_column='cod_pacote_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Pacote_Conta'),
        ),
        migrations.CreateModel(
            name='Auditoria_Status_Composicao_Competencia',
            fields=[
                ('cod_auditoria_composicao', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('tipo_prazo', models.CharField(blank=True, max_length=2, null=True)),
                ('data_lan_auditoria', models.DateField(auto_now_add=True)),
                ('data_competencia', models.DateField(blank=True, null=True)),
                ('obs_status', models.CharField(blank=True, max_length=300, null=True)),
                ('cod_contrato', models.ForeignKey(db_column='cod_contrato', on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Contrato')),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_contabil_auditorias_status_composicao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Anexos_Conta',
            fields=[
                ('cod_anexo_conta', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_anexo', models.CharField(max_length=80)),
                ('caminho_anexo', models.CharField(max_length=200)),
                ('ordem_anexo', models.IntegerField()),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
            ],
            options={
                'db_table': 'op_contabil_anexos_conta',
                'managed': True,
            },
        ),
    ]
