# Generated by Django 3.0.5 on 2023-11-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0003_auto_20231110_1331'),
        ('estrut_org_app', '0002_auto_20231110_1331'),
        ('contabil_composicao_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexos_Contrato',
            fields=[
                ('cod_anexo_contrato', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_competencia', models.DateField(blank=True, null=True)),
                ('desc_anexo', models.CharField(max_length=80)),
                ('caminho_anexo', models.CharField(max_length=200)),
                ('ordem_anexo', models.IntegerField()),
                ('cod_conta', models.ForeignKey(blank=True, db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
            ],
            options={
                'db_table': 'op_contabil_anexos_contrato',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Arquivo_Docs_Contas_Modelo_1',
            fields=[
                ('cod_arquivo', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('qtd_reg_imp', models.IntegerField(blank=True, null=True)),
                ('data_imp', models.DateTimeField(auto_now_add=True)),
                ('nome_arqv_original', models.CharField(max_length=200)),
                ('nome_arquivo_importado', models.CharField(max_length=200)),
                ('erro', models.CharField(max_length=1)),
                ('data_competencia', models.DateField(blank=True, null=True)),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_contabil_arqv_imp_contas_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Campos_Contas_Modelo_1',
            fields=[
                ('cod_campo', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_campo', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_campo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'op_contabil_campos_contas_modelo_1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Layout_Campos_Contas_Modelo_1',
            fields=[
                ('cod_lay_pac_camp', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('num_posicao_campo', models.IntegerField(blank=True, null=True)),
                ('cod_campo', models.ForeignKey(db_column='cod_campo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Campos_Contas_Modelo_1')),
            ],
            options={
                'db_table': 'op_contabil_lay_camp_contas_modelo_1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Layout_Importacao_Contas_Modelo_1',
            fields=[
                ('cod_layout', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_layout', models.CharField(blank=True, max_length=70, null=True)),
                ('data_ini_vig', models.DateField(blank=True, null=True)),
                ('data_fim_vig', models.DateField(blank=True, null=True)),
                ('qtd_campos', models.IntegerField(null=True)),
                ('tipo_pesq', models.CharField(max_length=1)),
                ('cod_empresa', models.ForeignKey(db_column='cod_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Empresa')),
            ],
            options={
                'db_table': 'op_contabil_layout_imp_contas_modelo_1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Registros_Arqv_Docs_Contas_Modelo_1',
            fields=[
                ('cod_reg', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('num_linha', models.IntegerField()),
                ('val_linha', models.CharField(max_length=200)),
                ('cod_arquivo', models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Contas_Modelo_1')),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_lay_pac_camp', models.ForeignKey(db_column='cod_lay_pac_camp', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Layout_Campos_Contas_Modelo_1')),
            ],
            options={
                'db_table': 'op_contabil_reg_arqv_contas_m1',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='auditoria_status_composicao_competencia',
            name='cod_conta',
            field=models.ForeignKey(blank=True, db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta'),
        ),
        migrations.AddField(
            model_name='auditoria_status_composicao_competencia',
            name='val_balancete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='auditoria_status_composicao_competencia',
            name='val_composicao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='auditoria_status_composicao_competencia',
            name='val_diferenca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pacote_conta',
            name='cod_modelo',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcela_contrato',
            name='val_fundo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria_status_composicao_competencia',
            name='cod_contrato',
            field=models.ForeignKey(blank=True, db_column='cod_contrato', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='val_liquido',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='val_nominal',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='parcela_contrato',
            name='data_liquidacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcela_contrato',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcela_contrato',
            name='natureza',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='parcela_contrato',
            name='val_conta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parcela_contrato',
            name='val_corrigido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parcela_contrato',
            name='val_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parcela_contrato',
            name='val_principal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='Anexos_Conta',
        ),
        migrations.AddField(
            model_name='layout_importacao_contas_modelo_1',
            name='cod_pacote_conta',
            field=models.ForeignKey(db_column='cod_pacote_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Pacote_Conta'),
        ),
        migrations.AddField(
            model_name='layout_importacao_contas_modelo_1',
            name='cod_usu',
            field=models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario'),
        ),
        migrations.AddField(
            model_name='layout_campos_contas_modelo_1',
            name='cod_layout',
            field=models.ForeignKey(db_column='cod_layout', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Layout_Importacao_Contas_Modelo_1'),
        ),
        migrations.AddField(
            model_name='anexos_contrato',
            name='cod_contrato',
            field=models.ForeignKey(blank=True, db_column='cod_contrato', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Contrato'),
        ),
    ]
