# Generated by Django 3.0.5 on 2023-11-20 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estrut_org_app', '0002_auto_20231110_1331'),
        ('usuario_app', '0003_auto_20231110_1331'),
        ('contabil_composicao_app', '0002_auto_20231117_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs_Pac_Tributos_M1_View',
            fields=[
                ('cod_pac_doc_tributos', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(blank=True, null=True)),
                ('nome_fornecedor', models.CharField(max_length=70)),
                ('num_doc', models.CharField(max_length=15)),
                ('num_doc_contabil', models.CharField(max_length=15)),
                ('val_rel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_razao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_dif', models.DecimalField(decimal_places=2, max_digits=8)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('historico', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_tributos_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docs_Pac_Folha_Pag_M1_View',
            fields=[
                ('cod_pac_doc_folha_pag', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_lancto', models.DateTimeField(blank=True, null=True)),
                ('matricula', models.CharField(max_length=15)),
                ('historico', models.CharField(blank=True, max_length=200, null=True)),
                ('num_doc', models.CharField(max_length=15)),
                ('num_doc_contabil', models.CharField(max_length=15)),
                ('val_rel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_razao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_dif', models.DecimalField(decimal_places=2, max_digits=8)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_folha_pag_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docs_Pac_Finac_Disponib_M1_View',
            fields=[
                ('cod_pac_doc_financ_disp', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('num_doc', models.CharField(max_length=15)),
                ('data_lancto', models.DateTimeField(blank=True, null=True)),
                ('val_rel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_razao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_dif', models.DecimalField(decimal_places=2, max_digits=8)),
                ('historico', models.CharField(blank=True, max_length=200, null=True)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_financ_disp_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docs_Pac_Estoque_M1_View',
            fields=[
                ('cod_doc_estoque', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome_almoxarifado', models.CharField(max_length=70)),
                ('cod_produto', models.IntegerField()),
                ('desc_produto', models.CharField(max_length=70)),
                ('qtd_prod', models.IntegerField(max_length=70)),
                ('custo_medio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_rel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_razao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_dif', models.DecimalField(decimal_places=2, max_digits=8)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_estoque_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docs_Pac_Contas_Pagar_Receber_M1_View',
            fields=[
                ('cod_pac_doc_contas_pagar_receber', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_lancto', models.DateTimeField(blank=True, null=True)),
                ('cnpj', models.CharField(max_length=18)),
                ('nome_fornecedor', models.CharField(max_length=70)),
                ('num_doc', models.CharField(max_length=15)),
                ('num_ap', models.CharField(max_length=15)),
                ('data_venc', models.DateField(blank=True, null=True)),
                ('val_rel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_razao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_dif', models.DecimalField(decimal_places=2, max_digits=8)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_contas_pagar_receber_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docs_Pac_Contas_Compensacao_M1_View',
            fields=[
                ('cod_pac_doc_contas_compensacao', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(blank=True, null=True)),
                ('cnpj', models.CharField(max_length=18)),
                ('nome_fornecedor', models.CharField(max_length=70)),
                ('num_doc', models.CharField(max_length=15)),
                ('num_doc_contabil', models.CharField(max_length=15)),
                ('val_rel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_razao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_dif', models.DecimalField(decimal_places=2, max_digits=8)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('historico', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_contas_compensacao_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Arquivo_Docs_Pac_Contas_Modelo_1',
            fields=[
                ('cod_arquivo', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('qtd_reg_imp', models.IntegerField(blank=True, null=True)),
                ('data_imp', models.DateTimeField(auto_now_add=True)),
                ('nome_arqv_original', models.CharField(max_length=200)),
                ('nome_arquivo_importado', models.CharField(max_length=200)),
                ('erro', models.CharField(max_length=1)),
                ('data_competencia', models.DateField(blank=True, null=True)),
                ('cod_pacote_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Pacote_Conta')),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_contabil_arqv_doc_pac_contas_m1',
                'managed': True,
            },
        ),
    ]
