# Generated by Django 3.0.5 on 2023-11-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabil_composicao_app', '0003_arquivo_docs_pac_contas_modelo_1_docs_pac_contas_compensacao_m1_view_docs_pac_contas_pagar_receber_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs_pac_estoque_m1_view',
            name='qtd_prod',
            field=models.IntegerField(),
        ),
    ]
