# Generated by Django 3.0.5 on 2023-11-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabil_composicao_app', '0004_auto_20231120_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docs_pac_estoque_m1_view',
            old_name='cod_doc_estoque',
            new_name='cod_pac_doc_estoque',
        ),
    ]
