# Generated by Django 3.0.5 on 2023-11-22 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estrut_org_app', '0002_auto_20231110_1331'),
        ('contabil_composicao_app', '0005_auto_20231121_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs_pac_contas_compensacao_m1_view',
            name='cod_arquivo',
            field=models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1'),
        ),
        migrations.AddField(
            model_name='docs_pac_contas_pagar_receber_m1_view',
            name='cod_arquivo',
            field=models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1'),
        ),
        migrations.AddField(
            model_name='docs_pac_contas_pagar_receber_m1_view',
            name='num_parc',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docs_pac_estoque_m1_view',
            name='cod_arquivo',
            field=models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1'),
        ),
        migrations.AddField(
            model_name='docs_pac_estoque_m1_view',
            name='cod_filial',
            field=models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial'),
        ),
        migrations.AddField(
            model_name='docs_pac_finac_disponib_m1_view',
            name='cod_arquivo',
            field=models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1'),
        ),
        migrations.AddField(
            model_name='docs_pac_folha_pag_m1_view',
            name='cod_arquivo',
            field=models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1'),
        ),
        migrations.AddField(
            model_name='docs_pac_tributos_m1_view',
            name='cod_arquivo',
            field=models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1'),
        ),
        migrations.CreateModel(
            name='Docs_Pac_Intercompany_M1_View',
            fields=[
                ('cod_pac_doc_intercompany', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('num_doc', models.CharField(max_length=15)),
                ('data_lancto', models.DateTimeField(blank=True, null=True)),
                ('val_rel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_razao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_dif', models.DecimalField(decimal_places=2, max_digits=8)),
                ('historico', models.CharField(blank=True, max_length=200, null=True)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_arquivo', models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1')),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_intercompany_disp_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docs_Pac_Imobilizado_M1_View',
            fields=[
                ('cod_pac_doc_imobilizado', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('plaqueta', models.CharField(max_length=15)),
                ('desc_imobilizado', models.CharField(max_length=80)),
                ('val_aquisicao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('num_doc', models.CharField(max_length=15)),
                ('nome_fornecedor', models.CharField(max_length=80)),
                ('depreciacao_acum', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_liq', models.DecimalField(decimal_places=2, max_digits=8)),
                ('taxa_depreciacao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_rel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_razao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_dif', models.DecimalField(decimal_places=2, max_digits=8)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_arquivo', models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1')),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_imobilizado_disp_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docs_Pac_Consorcio_Ativo_M1_View',
            fields=[
                ('cod_pac_doc_consorcio_ativo', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('num_doc', models.CharField(max_length=15)),
                ('data_lancto', models.DateTimeField(blank=True, null=True)),
                ('val_rel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_razao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_dif', models.DecimalField(decimal_places=2, max_digits=8)),
                ('historico', models.CharField(blank=True, max_length=200, null=True)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_arquivo', models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1')),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_consorcio_ativo_disp_m1',
                'managed': True,
            },
        ),
    ]
