# Generated by Django 3.0.5 on 2024-01-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estrut_org_app', '0003_projeto_cod_reduzido_benner'),
        ('contabil_composicao_app', '0006_auto_20231122_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs_pac_imobilizado_m1_view',
            name='data_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arquivo_docs_pac_contas_modelo_1',
            name='cod_pacote_conta',
            field=models.ForeignKey(db_column='cod_pacote_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Pacote_Conta'),
        ),
        migrations.AlterField(
            model_name='docs_pac_consorcio_ativo_m1_view',
            name='data_lancto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docs_pac_consorcio_ativo_m1_view',
            name='val_dif',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_consorcio_ativo_m1_view',
            name='val_razao',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_consorcio_ativo_m1_view',
            name='val_rel',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_contas_compensacao_m1_view',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docs_pac_contas_compensacao_m1_view',
            name='data_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docs_pac_contas_compensacao_m1_view',
            name='val_dif',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_contas_compensacao_m1_view',
            name='val_razao',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_contas_compensacao_m1_view',
            name='val_rel',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_contas_pagar_receber_m1_view',
            name='data_lancto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docs_pac_contas_pagar_receber_m1_view',
            name='num_doc',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='docs_pac_contas_pagar_receber_m1_view',
            name='val_dif',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_contas_pagar_receber_m1_view',
            name='val_razao',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_contas_pagar_receber_m1_view',
            name='val_rel',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_estoque_m1_view',
            name='custo_medio',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_estoque_m1_view',
            name='val_dif',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_estoque_m1_view',
            name='val_razao',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_estoque_m1_view',
            name='val_rel',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_finac_disponib_m1_view',
            name='data_lancto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docs_pac_finac_disponib_m1_view',
            name='val_dif',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_finac_disponib_m1_view',
            name='val_razao',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_finac_disponib_m1_view',
            name='val_rel',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_folha_pag_m1_view',
            name='data_lancto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docs_pac_folha_pag_m1_view',
            name='val_dif',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_folha_pag_m1_view',
            name='val_razao',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_folha_pag_m1_view',
            name='val_rel',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_imobilizado_m1_view',
            name='depreciacao_acum',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_imobilizado_m1_view',
            name='taxa_depreciacao',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_imobilizado_m1_view',
            name='val_aquisicao',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_imobilizado_m1_view',
            name='val_dif',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_imobilizado_m1_view',
            name='val_liq',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_imobilizado_m1_view',
            name='val_razao',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_imobilizado_m1_view',
            name='val_rel',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_intercompany_m1_view',
            name='data_lancto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docs_pac_intercompany_m1_view',
            name='val_dif',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_intercompany_m1_view',
            name='val_razao',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_intercompany_m1_view',
            name='val_rel',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_tributos_m1_view',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docs_pac_tributos_m1_view',
            name='data_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docs_pac_tributos_m1_view',
            name='nome_fornecedor',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='docs_pac_tributos_m1_view',
            name='num_doc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='docs_pac_tributos_m1_view',
            name='num_doc_contabil',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='docs_pac_tributos_m1_view',
            name='val_dif',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_tributos_m1_view',
            name='val_razao',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='docs_pac_tributos_m1_view',
            name='val_rel',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.CreateModel(
            name='Docs_Demais_Contas_M1_View',
            fields=[
                ('cod_pac_doc_outros', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('data_lancto', models.DateField(blank=True, null=True)),
                ('historico', models.CharField(blank=True, max_length=200, null=True)),
                ('num_doc', models.CharField(max_length=15)),
                ('num_doc_contabil', models.CharField(max_length=15)),
                ('val_rel', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_razao', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_dif', models.DecimalField(decimal_places=4, max_digits=12)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_arquivo', models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1')),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_outros_m1',
                'managed': True,
            },
        ),
    ]
