# Generated by Django 3.0.5 on 2024-09-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estrut_org_app', '0004_filial_tem_calculo_rv'),
        ('usuario_app', '0005_liberacao_usuario_projeto_benner_cod_empresa'),
        ('contabil_composicao_app', '0007_auto_20240117_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs_Demais_Contas_M1',
            fields=[
                ('cod_pac_doc_outros', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('data_lancto', models.DateField(blank=True, null=True)),
                ('historico', models.CharField(blank=True, max_length=200, null=True)),
                ('num_doc', models.CharField(max_length=25)),
                ('num_doc_contabil', models.CharField(max_length=15)),
                ('val_rel', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_razao', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_dif', models.DecimalField(decimal_places=4, max_digits=12)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('ativo', models.CharField(default='S', max_length=1)),
                ('cod_arquivo', models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1')),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_outros_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docs_Pac_Consorcio_Ativo_M1',
            fields=[
                ('cod_pac_doc_consorcio_ativo', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('num_doc', models.CharField(max_length=15)),
                ('data_lancto', models.DateField(blank=True, null=True)),
                ('val_rel', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_razao', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_dif', models.DecimalField(decimal_places=4, max_digits=12)),
                ('historico', models.CharField(blank=True, max_length=200, null=True)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('ativo', models.CharField(default='S', max_length=1)),
                ('cod_arquivo', models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1')),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_consorcio_ativo_disp_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docs_Pac_Contas_Compensacao_M1',
            fields=[
                ('cod_pac_doc_contas_compensacao', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('nome_fornecedor', models.CharField(blank=True, max_length=70, null=True)),
                ('num_doc', models.CharField(blank=True, max_length=15, null=True)),
                ('num_doc_contabil', models.CharField(blank=True, max_length=15, null=True)),
                ('val_rel', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_razao', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_dif', models.DecimalField(decimal_places=4, max_digits=12)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('ativo', models.CharField(default='S', max_length=1)),
                ('historico', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_arquivo', models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1')),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_contas_compensacao_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docs_Pac_Contas_Pagar_Receber_M1',
            fields=[
                ('cod_pac_doc_contas_pagar_receber', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_lancto', models.DateField(blank=True, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('nome_fornecedor', models.CharField(blank=True, max_length=70, null=True)),
                ('num_doc', models.CharField(blank=True, max_length=30, null=True)),
                ('num_ap', models.CharField(blank=True, max_length=15, null=True)),
                ('num_parc', models.CharField(blank=True, max_length=15, null=True)),
                ('data_venc', models.DateField(blank=True, null=True)),
                ('val_rel', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('val_razao', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('val_dif', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('ativo', models.CharField(default='S', max_length=1)),
                ('cod_arquivo', models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1')),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_contas_pagar_receber_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docs_Pac_Estoque_M1',
            fields=[
                ('cod_pac_doc_estoque', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome_almoxarifado', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('desc_produto', models.CharField(blank=True, max_length=70, null=True)),
                ('qtd_prod', models.IntegerField(blank=True, null=True)),
                ('custo_medio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_rel', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_razao', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_dif', models.DecimalField(decimal_places=4, max_digits=12)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('ativo', models.CharField(default='S', max_length=1)),
                ('cod_arquivo', models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1')),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_estoque_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docs_Pac_Finac_Disponib_M1',
            fields=[
                ('cod_pac_doc_financ_disp', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('num_doc', models.CharField(max_length=15)),
                ('data_lancto', models.DateField(blank=True, null=True)),
                ('val_rel', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_razao', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_dif', models.DecimalField(decimal_places=4, max_digits=12)),
                ('historico', models.CharField(blank=True, max_length=200, null=True)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('ativo', models.CharField(default='S', max_length=1)),
                ('cod_arquivo', models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1')),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_financ_disp_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docs_Pac_Folha_Pag_M1',
            fields=[
                ('cod_pac_doc_folha_pag', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_lancto', models.DateField(blank=True, null=True)),
                ('matricula', models.CharField(max_length=15)),
                ('historico', models.CharField(blank=True, max_length=200, null=True)),
                ('num_doc', models.CharField(max_length=15)),
                ('num_doc_contabil', models.CharField(max_length=15)),
                ('val_rel', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_razao', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_dif', models.DecimalField(decimal_places=4, max_digits=12)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('ativo', models.CharField(default='S', max_length=1)),
                ('cod_arquivo', models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1')),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_folha_pag_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docs_Pac_Imobilizado_M1',
            fields=[
                ('cod_pac_doc_imobilizado', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('plaqueta', models.CharField(max_length=15)),
                ('desc_imobilizado', models.CharField(max_length=80)),
                ('val_aquisicao', models.DecimalField(decimal_places=4, max_digits=12)),
                ('num_doc', models.CharField(max_length=15)),
                ('nome_fornecedor', models.CharField(max_length=80)),
                ('depreciacao_acum', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_liq', models.DecimalField(decimal_places=4, max_digits=12)),
                ('taxa_depreciacao', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_rel', models.DecimalField(decimal_places=4, max_digits=14)),
                ('val_razao', models.DecimalField(decimal_places=4, max_digits=14)),
                ('val_dif', models.DecimalField(decimal_places=4, max_digits=12)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('ativo', models.CharField(default='S', max_length=1)),
                ('cod_arquivo', models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1')),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_imobilizado_disp_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docs_Pac_Intercompany_M1',
            fields=[
                ('cod_pac_doc_intercompany', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('num_doc', models.CharField(max_length=15)),
                ('data_lancto', models.DateField(blank=True, null=True)),
                ('val_rel', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_razao', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_dif', models.DecimalField(decimal_places=4, max_digits=12)),
                ('historico', models.CharField(blank=True, max_length=200, null=True)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('ativo', models.CharField(default='S', max_length=1)),
                ('cod_arquivo', models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1')),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_intercompany_disp_m1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docs_Pac_Tributos_M1',
            fields=[
                ('cod_pac_doc_tributos', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('nome_fornecedor', models.CharField(blank=True, max_length=150, null=True)),
                ('num_doc', models.CharField(blank=True, max_length=25, null=True)),
                ('num_doc_contabil', models.CharField(blank=True, max_length=25, null=True)),
                ('val_rel', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_razao', models.DecimalField(decimal_places=4, max_digits=12)),
                ('val_dif', models.DecimalField(decimal_places=4, max_digits=12)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('historico', models.CharField(blank=True, max_length=200, null=True)),
                ('ativo', models.CharField(default='S', max_length=1)),
                ('cod_arquivo', models.ForeignKey(db_column='cod_arquivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Arquivo_Docs_Pac_Contas_Modelo_1')),
                ('cod_conta', models.ForeignKey(db_column='cod_conta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabil_composicao_app.Conta')),
                ('cod_filial', models.ForeignKey(db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'op_contabil_docs_pac_tributos_m1',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='docs_pac_consorcio_ativo_m1_view',
            name='cod_arquivo',
        ),
        migrations.RemoveField(
            model_name='docs_pac_consorcio_ativo_m1_view',
            name='cod_conta',
        ),
        migrations.RemoveField(
            model_name='docs_pac_consorcio_ativo_m1_view',
            name='cod_filial',
        ),
        migrations.RemoveField(
            model_name='docs_pac_contas_compensacao_m1_view',
            name='cod_arquivo',
        ),
        migrations.RemoveField(
            model_name='docs_pac_contas_compensacao_m1_view',
            name='cod_conta',
        ),
        migrations.RemoveField(
            model_name='docs_pac_contas_compensacao_m1_view',
            name='cod_filial',
        ),
        migrations.RemoveField(
            model_name='docs_pac_contas_pagar_receber_m1_view',
            name='cod_arquivo',
        ),
        migrations.RemoveField(
            model_name='docs_pac_contas_pagar_receber_m1_view',
            name='cod_conta',
        ),
        migrations.RemoveField(
            model_name='docs_pac_contas_pagar_receber_m1_view',
            name='cod_filial',
        ),
        migrations.RemoveField(
            model_name='docs_pac_estoque_m1_view',
            name='cod_arquivo',
        ),
        migrations.RemoveField(
            model_name='docs_pac_estoque_m1_view',
            name='cod_conta',
        ),
        migrations.RemoveField(
            model_name='docs_pac_estoque_m1_view',
            name='cod_filial',
        ),
        migrations.RemoveField(
            model_name='docs_pac_finac_disponib_m1_view',
            name='cod_arquivo',
        ),
        migrations.RemoveField(
            model_name='docs_pac_finac_disponib_m1_view',
            name='cod_conta',
        ),
        migrations.RemoveField(
            model_name='docs_pac_finac_disponib_m1_view',
            name='cod_filial',
        ),
        migrations.RemoveField(
            model_name='docs_pac_folha_pag_m1_view',
            name='cod_arquivo',
        ),
        migrations.RemoveField(
            model_name='docs_pac_folha_pag_m1_view',
            name='cod_conta',
        ),
        migrations.RemoveField(
            model_name='docs_pac_folha_pag_m1_view',
            name='cod_filial',
        ),
        migrations.RemoveField(
            model_name='docs_pac_imobilizado_m1_view',
            name='cod_arquivo',
        ),
        migrations.RemoveField(
            model_name='docs_pac_imobilizado_m1_view',
            name='cod_conta',
        ),
        migrations.RemoveField(
            model_name='docs_pac_imobilizado_m1_view',
            name='cod_filial',
        ),
        migrations.RemoveField(
            model_name='docs_pac_intercompany_m1_view',
            name='cod_arquivo',
        ),
        migrations.RemoveField(
            model_name='docs_pac_intercompany_m1_view',
            name='cod_conta',
        ),
        migrations.RemoveField(
            model_name='docs_pac_intercompany_m1_view',
            name='cod_filial',
        ),
        migrations.RemoveField(
            model_name='docs_pac_tributos_m1_view',
            name='cod_arquivo',
        ),
        migrations.RemoveField(
            model_name='docs_pac_tributos_m1_view',
            name='cod_conta',
        ),
        migrations.RemoveField(
            model_name='docs_pac_tributos_m1_view',
            name='cod_filial',
        ),
        migrations.AddField(
            model_name='anexos_contrato',
            name='cod_usu',
            field=models.ForeignKey(db_column='cod_usu', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anexos_contrato',
            name='eh_anexo_principal_competencia',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='parcela_contrato',
            name='cod_usu',
            field=models.ForeignKey(db_column='cod_usu', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcela_contrato',
            name='data_ultima_atualizacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcela_contrato',
            name='obs_parcela',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='parcela_contrato',
            name='val_acres_principal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parcela_contrato',
            name='val_acres_taxas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parcela_contrato',
            name='val_desc_principal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parcela_contrato',
            name='val_desc_taxas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='handle_fn_doc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsaveis_conta',
            name='data_fim_atividade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsaveis_conta',
            name='data_ini_atividade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Docs_Demais_Contas_M1_View',
        ),
        migrations.DeleteModel(
            name='Docs_Pac_Consorcio_Ativo_M1_View',
        ),
        migrations.DeleteModel(
            name='Docs_Pac_Contas_Compensacao_M1_View',
        ),
        migrations.DeleteModel(
            name='Docs_Pac_Contas_Pagar_Receber_M1_View',
        ),
        migrations.DeleteModel(
            name='Docs_Pac_Estoque_M1_View',
        ),
        migrations.DeleteModel(
            name='Docs_Pac_Finac_Disponib_M1_View',
        ),
        migrations.DeleteModel(
            name='Docs_Pac_Folha_Pag_M1_View',
        ),
        migrations.DeleteModel(
            name='Docs_Pac_Imobilizado_M1_View',
        ),
        migrations.DeleteModel(
            name='Docs_Pac_Intercompany_M1_View',
        ),
        migrations.DeleteModel(
            name='Docs_Pac_Tributos_M1_View',
        ),
    ]
