# Generated by Django 3.0.5 on 2024-09-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_app', '0005_liberacao_usuario_projeto_benner_cod_empresa'),
        ('estrut_org_app', '0004_filial_tem_calculo_rv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos_Freightech',
            fields=[
                ('cod_cargo_freightech', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('grupo_cargo', models.CharField(max_length=20)),
                ('desc_cargo', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'op_freightech_cargos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plan_Remunerada_Freightech',
            fields=[
                ('cod_plan_rem_freigh', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_arq_imp', models.DateField(auto_now_add=True)),
                ('hora_arq_imp', models.TimeField(auto_now_add=True)),
                ('nome_arq_original', models.CharField(max_length=500, null=True)),
                ('nome_arq_imp', models.CharField(max_length=500, null=True)),
                ('lista_colunas', models.CharField(blank=True, max_length=500, null=True)),
                ('qtd_colunas', models.IntegerField(blank=True, default=0, null=True)),
                ('qtd_registros', models.IntegerField(blank=True, default=0, null=True)),
                ('qtd_importados', models.IntegerField(blank=True, default=0, null=True)),
                ('qtd_atualizados', models.IntegerField(blank=True, default=0, null=True)),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_freightech_plan_remuneracao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Relacao_Cargos_Freightech_Senior',
            fields=[
                ('cod_rel_cargo_freightech_senior', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('cod_cargo_senior', models.IntegerField()),
                ('desc_cargo_senior', models.CharField(max_length=80)),
                ('cod_cargo_freightech', models.ForeignKey(db_column='cod_cargo_freightech', on_delete=django.db.models.deletion.DO_NOTHING, to='freightech_remunerado_qlp_app.Cargos_Freightech')),
                ('cod_projeto', models.ForeignKey(db_column='cod_projeto', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Projeto')),
            ],
            options={
                'db_table': 'op_freightech_rel_cargos_freightech_senior',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Registros_Plan_Remunerado_Freightech_Rota_Equipe_Beneficios',
            fields=[
                ('cod_qlp_rem_rota_adm', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_beneficio', models.CharField(max_length=30)),
                ('vigencia', models.DateField()),
                ('quinzena', models.IntegerField(default=0)),
                ('turno', models.CharField(max_length=20)),
                ('desc_cargo', models.CharField(max_length=80)),
                ('val_total_beneficio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('eh_noturna', models.CharField(default='N', max_length=1)),
                ('id_reg_plan', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('cod_filial_promax', models.CharField(max_length=10)),
                ('cod_cargo_freightech', models.ForeignKey(blank=True, db_column='cod_cargo_freightech', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='freightech_remunerado_qlp_app.Cargos_Freightech')),
                ('cod_plan_rem_freigh', models.ForeignKey(db_column='cod_plan_rem_freigh', on_delete=django.db.models.deletion.DO_NOTHING, to='freightech_remunerado_qlp_app.Plan_Remunerada_Freightech')),
                ('cod_projeto', models.ForeignKey(db_column='cod_projeto', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Projeto')),
            ],
            options={
                'db_table': 'op_freightech_plan_remuneracao_rota_equipe_beneficios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Registros_Plan_Remunerado_Freightech_Rota_Equipe',
            fields=[
                ('cod_qlp_rem_rota_adm', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('vigencia', models.DateField()),
                ('quinzena', models.IntegerField(default=0)),
                ('turno', models.CharField(max_length=20)),
                ('grupo_cargo', models.CharField(max_length=20)),
                ('desc_cargo', models.CharField(max_length=80)),
                ('qtd_dsr', models.IntegerField(blank=True, null=True)),
                ('qtd_horas_extra_fixa', models.IntegerField(blank=True, null=True)),
                ('perc_abs', models.DecimalField(decimal_places=2, max_digits=8)),
                ('perc_encargo_prov', models.DecimalField(decimal_places=2, max_digits=8)),
                ('perc_turn_over', models.DecimalField(decimal_places=2, max_digits=8)),
                ('premiacao_plus', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qtd_total_por_caminhao_ativo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qtd_por_caminhao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_rem_fixa_contra_cheque', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_total_ordenado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_total_remuneracao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_total_remuneracao_com_beneficio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_reg_plan', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('cod_filial_promax', models.CharField(max_length=10)),
                ('cod_cargo_freightech', models.ForeignKey(blank=True, db_column='cod_cargo_freightech', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='freightech_remunerado_qlp_app.Cargos_Freightech')),
                ('cod_plan_rem_freigh', models.ForeignKey(db_column='cod_plan_rem_freigh', on_delete=django.db.models.deletion.DO_NOTHING, to='freightech_remunerado_qlp_app.Plan_Remunerada_Freightech')),
                ('cod_projeto', models.ForeignKey(db_column='cod_projeto', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Projeto')),
            ],
            options={
                'db_table': 'op_freightech_plan_remuneracao_rota_equipe',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Registros_Plan_Remunerado_Freightech_Rota_Adm',
            fields=[
                ('cod_qlp_rem_rota_adm', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('vigencia', models.DateField()),
                ('quinzena', models.IntegerField(default=0)),
                ('grupo_cargo', models.CharField(max_length=20)),
                ('desc_cargo', models.CharField(max_length=80)),
                ('val_unit_beneficio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_unit_encargos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_unit_frota_leve', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_unit_ordenados', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_unit_telefonia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_unit_uniformes', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_bench_salarios', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qtd_qlp_bench', models.IntegerField(default=0)),
                ('qtd_beneficios', models.IntegerField(default=0)),
                ('qtd_encargos', models.IntegerField(default=0)),
                ('qtd_frota_leve', models.IntegerField(default=0)),
                ('qtd_ordenados', models.IntegerField(default=0)),
                ('qtd_telefonia', models.IntegerField(default=0)),
                ('qtd_uniformes', models.IntegerField(default=0)),
                ('id_reg_plan', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('cod_filial_promax', models.CharField(max_length=10)),
                ('cod_cargo_freightech', models.ForeignKey(blank=True, db_column='cod_cargo_freightech', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='freightech_remunerado_qlp_app.Cargos_Freightech')),
                ('cod_plan_rem_freigh', models.ForeignKey(db_column='cod_plan_rem_freigh', on_delete=django.db.models.deletion.DO_NOTHING, to='freightech_remunerado_qlp_app.Plan_Remunerada_Freightech')),
                ('cod_projeto', models.ForeignKey(db_column='cod_projeto', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Projeto')),
            ],
            options={
                'db_table': 'op_freightech_plan_remuneracao_rota_adm',
                'managed': True,
            },
        ),
    ]
