# Generated by Django 3.0.5 on 2024-09-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freightech_remunerado_qlp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros_Plan_Remunerado_Freightech_Rota_Equipe_Entrega_Beneficios',
            fields=[
                ('cod_qlp_rem_rota_adm', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome_unidade', models.CharField(max_length=30)),
                ('desc_beneficio', models.CharField(max_length=30)),
                ('vigencia', models.DateField()),
                ('quinzena', models.IntegerField(default=0)),
                ('turno', models.CharField(max_length=20)),
                ('val_total_beneficio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('eh_noturna', models.CharField(default='N', max_length=1)),
                ('id_reg_plan', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('cod_cargo_freightech', models.ForeignKey(blank=True, db_column='cod_cargo_freightech', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='freightech_remunerado_qlp_app.Cargos_Freightech')),
            ],
            options={
                'db_table': 'op_freightech_plan_remuneracao_rota_equipe_entrega_beneficios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Registros_Plan_Remunerado_Freightech_Rota_Qlp_Adm',
            fields=[
                ('cod_qlp_rem_rota_adm', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('vigencia', models.DateField()),
                ('quinzena', models.IntegerField(default=0)),
                ('nome_unidade', models.CharField(max_length=30)),
                ('val_unit_beneficio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_unit_encargos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_unit_frota_leve', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_unit_ordenados', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_unit_telefonia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_unit_uniformes', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_bench_salarios', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qtd_qlp_bench', models.IntegerField(default=0)),
                ('qtd_beneficios', models.IntegerField(default=0)),
                ('qtd_encargos', models.IntegerField(default=0)),
                ('qtd_frota_leve', models.IntegerField(default=0)),
                ('qtd_ordenados', models.IntegerField(default=0)),
                ('qtd_telefonia', models.IntegerField(default=0)),
                ('qtd_uniformes', models.IntegerField(default=0)),
                ('id_reg_plan', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('cod_cargo_freightech', models.ForeignKey(blank=True, db_column='cod_cargo_freightech', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='freightech_remunerado_qlp_app.Cargos_Freightech')),
            ],
            options={
                'db_table': 'op_freightech_plan_remuneracao_rota_qlp_adm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Registros_Plan_Remunerado_Freightech_Rota_Qlp_Equipe_Entrega',
            fields=[
                ('cod_qlp_rem_rota_adm', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome_unidade', models.CharField(max_length=30)),
                ('vigencia', models.DateField()),
                ('quinzena', models.IntegerField(default=0)),
                ('turno', models.CharField(max_length=20)),
                ('qtd_dsr', models.IntegerField(blank=True, null=True)),
                ('hora_extra_fixa', models.IntegerField(blank=True, null=True)),
                ('qtd_horas_extra_fixa', models.IntegerField(blank=True, null=True)),
                ('val_outros', models.DecimalField(decimal_places=2, max_digits=8)),
                ('perc_abs', models.DecimalField(decimal_places=2, max_digits=8)),
                ('perc_encargo_prov', models.DecimalField(decimal_places=2, max_digits=8)),
                ('perc_hora_extra', models.DecimalField(decimal_places=2, max_digits=8)),
                ('perc_turn_over', models.DecimalField(decimal_places=2, max_digits=8)),
                ('premiacao_plus', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qtd_total_por_caminhao_ativo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qtd_por_caminhao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_rem_fixa_contra_cheque', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_total_ordenado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_total_remuneracao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('val_total_remuneracao_com_beneficio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_reg_plan', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('cod_cargo_freightech', models.ForeignKey(blank=True, db_column='cod_cargo_freightech', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='freightech_remunerado_qlp_app.Cargos_Freightech')),
            ],
            options={
                'db_table': 'op_freightech_plan_remuneracao_rota_qlp_equipe_entrega',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='registros_plan_remunerado_freightech_rota_equipe',
            name='cod_cargo_freightech',
        ),
        migrations.RemoveField(
            model_name='registros_plan_remunerado_freightech_rota_equipe',
            name='cod_plan_rem_freigh',
        ),
        migrations.RemoveField(
            model_name='registros_plan_remunerado_freightech_rota_equipe',
            name='cod_projeto',
        ),
        migrations.RemoveField(
            model_name='registros_plan_remunerado_freightech_rota_equipe_beneficios',
            name='cod_cargo_freightech',
        ),
        migrations.RemoveField(
            model_name='registros_plan_remunerado_freightech_rota_equipe_beneficios',
            name='cod_plan_rem_freigh',
        ),
        migrations.RemoveField(
            model_name='registros_plan_remunerado_freightech_rota_equipe_beneficios',
            name='cod_projeto',
        ),
        migrations.RemoveField(
            model_name='plan_remunerada_freightech',
            name='hora_arq_imp',
        ),
        migrations.RemoveField(
            model_name='plan_remunerada_freightech',
            name='lista_colunas',
        ),
        migrations.RemoveField(
            model_name='plan_remunerada_freightech',
            name='qtd_atualizados',
        ),
        migrations.RemoveField(
            model_name='plan_remunerada_freightech',
            name='qtd_colunas',
        ),
        migrations.RemoveField(
            model_name='plan_remunerada_freightech',
            name='qtd_importados',
        ),
        migrations.RemoveField(
            model_name='plan_remunerada_freightech',
            name='qtd_registros',
        ),
        migrations.AddField(
            model_name='plan_remunerada_freightech',
            name='desc_layout_arq',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='plan_remunerada_freightech',
            name='data_arq_imp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Registros_Plan_Remunerado_Freightech_Rota_Adm',
        ),
        migrations.DeleteModel(
            name='Registros_Plan_Remunerado_Freightech_Rota_Equipe',
        ),
        migrations.DeleteModel(
            name='Registros_Plan_Remunerado_Freightech_Rota_Equipe_Beneficios',
        ),
        migrations.AddField(
            model_name='registros_plan_remunerado_freightech_rota_qlp_equipe_entrega',
            name='cod_plan_rem_freigh',
            field=models.ForeignKey(db_column='cod_plan_rem_freigh', on_delete=django.db.models.deletion.DO_NOTHING, to='freightech_remunerado_qlp_app.Plan_Remunerada_Freightech'),
        ),
        migrations.AddField(
            model_name='registros_plan_remunerado_freightech_rota_qlp_adm',
            name='cod_plan_rem_freigh',
            field=models.ForeignKey(db_column='cod_plan_rem_freigh', on_delete=django.db.models.deletion.DO_NOTHING, to='freightech_remunerado_qlp_app.Plan_Remunerada_Freightech'),
        ),
        migrations.AddField(
            model_name='registros_plan_remunerado_freightech_rota_equipe_entrega_beneficios',
            name='cod_plan_rem_freigh',
            field=models.ForeignKey(db_column='cod_plan_rem_freigh', on_delete=django.db.models.deletion.DO_NOTHING, to='freightech_remunerado_qlp_app.Plan_Remunerada_Freightech'),
        ),
    ]
