# Generated by Django 3.0.5 on 2023-11-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_app', '0003_auto_20231110_1331'),
        ('estrut_org_app', '0002_auto_20231110_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libera_Filial_Check',
            fields=[
                ('cod_libera_filial', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('cod_check', models.IntegerField()),
                ('data_desativacao', models.DateTimeField(blank=True, null=True)),
                ('cod_filial', models.ForeignKey(blank=True, db_column='cod_filial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Filial')),
            ],
            options={
                'db_table': 'safe_check_libera_filial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Layout_Check',
            fields=[
                ('cod_check', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_check', models.CharField(max_length=70)),
                ('versao', models.IntegerField()),
                ('data_inclusao', models.DateTimeField(blank=True, null=True)),
                ('data_desativacao', models.DateTimeField(blank=True, null=True)),
                ('periodicidade', models.CharField(blank=True, max_length=1, null=True)),
                ('medida_periodicidade', models.IntegerField()),
                ('cod_usu', models.ForeignKey(blank=True, db_column='cod_usu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'safe_layout_check',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item_Check',
            fields=[
                ('cod_item_check', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_check', models.CharField(max_length=300)),
                ('tipo_resposta', models.IntegerField()),
                ('data_inclusao', models.DateTimeField(blank=True, null=True)),
                ('cod_usuario', models.IntegerField()),
                ('data_desativacao', models.DateTimeField(blank=True, null=True)),
                ('campo_obs_img', models.IntegerField()),
                ('ordem_item', models.IntegerField()),
                ('tipo_item', models.IntegerField()),
                ('cod_check', models.ForeignKey(blank=True, db_column='cod_check', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='safety_layout_checklist_app.Layout_Check')),
            ],
            options={
                'db_table': 'safe_item_check',
                'managed': True,
            },
        ),
    ]
