# Generated by Django 3.0.5 on 2023-11-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_layout_checklist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item_check',
            table='op_safety_item_check',
        ),
        migrations.AlterModelTable(
            name='layout_check',
            table='op_safety_layout_check',
        ),
        migrations.AlterModelTable(
            name='libera_filial_check',
            table='op_safety_check_libera_filial',
        ),
    ]
