# Generated by Django 3.0.5 on 2024-01-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_layout_checklist_app', '0002_auto_20231110_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout_check',
            name='tipo_check',
            field=models.CharField(default='empilhadeira', max_length=30),
            preserve_default=False,
        ),
    ]
