# Generated by Django 3.0.5 on 2024-09-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safety_layout_checklist_app', '0003_layout_check_tipo_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itens_Componentes',
            fields=[
                ('cod_componente', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('tipo_check', models.IntegerField()),
                ('campo_check', models.IntegerField()),
                ('cod_pai', models.IntegerField()),
                ('desc_componente', models.CharField(max_length=80)),
                ('cod_empresa', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'op_safe_itens_componentes_forms',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='item_check',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_check',
            name='obrigatorio',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layout_check',
            name='ativo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='layout_check',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item_check',
            name='tipo_resposta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libera_filial_check',
            name='cod_check',
            field=models.ForeignKey(blank=True, db_column='cod_check', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='safety_layout_checklist_app.Layout_Check'),
        ),
        migrations.AlterModelTable(
            name='item_check',
            table='op_safe_item_check',
        ),
        migrations.AlterModelTable(
            name='layout_check',
            table='op_safe_layout_check',
        ),
        migrations.AlterModelTable(
            name='libera_filial_check',
            table='op_safe_check_libera_filial',
        ),
    ]
