# Generated by Django 3.0.5 on 2023-08-15 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_app', '0001_initial'),
        ('estrut_org_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo_Indisponibilidade',
            fields=[
                ('cod_grupo_indisponibilidade', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_grupo_indisp', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'op_frota_indisp_grupo_indisponibilidade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sigla_Status_Disponibilidade_Frota',
            fields=[
                ('cod_sigla', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_sigla', models.CharField(max_length=35)),
                ('sigla', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'op_frota_indisp_siglas_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Frota_Contratada',
            fields=[
                ('cod_frota_contratada', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_lancamento', models.DateField(auto_now_add=True)),
                ('data_ref', models.DateField()),
                ('turno', models.CharField(blank=True, default='D', max_length=1, null=True)),
                ('dia_semana', models.IntegerField(default=0)),
                ('qtd_frota_contratada_ativa', models.IntegerField()),
                ('qtd_frota_contratada_parada', models.IntegerField()),
                ('cod_projeto', models.ForeignKey(db_column='cod_projeto', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Projeto')),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_frota_indisp_contratada',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Apontamento_Promax',
            fields=[
                ('cod_apontamento_promax', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data_lancamento', models.DateField(auto_now_add=True)),
                ('data_apontamento', models.DateField()),
                ('placa', models.CharField(max_length=7)),
                ('status_placa', models.CharField(default='DISPONÍVEL', max_length=30)),
                ('numero_os', models.CharField(blank=True, max_length=40, null=True)),
                ('justificativa', models.CharField(blank=True, max_length=300, null=True)),
                ('status_lanc', models.CharField(default='S', max_length=1)),
                ('cod_grupo_indisponibilidade', models.ForeignKey(blank=True, db_column='cod_grupo_indisponibilidade', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frota_disponibilidade_app.Grupo_Indisponibilidade')),
                ('cod_projeto', models.ForeignKey(db_column='cod_projeto', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Projeto')),
                ('cod_sigla', models.ForeignKey(db_column='cod_sigla', on_delete=django.db.models.deletion.DO_NOTHING, to='frota_disponibilidade_app.Sigla_Status_Disponibilidade_Frota')),
                ('cod_usu', models.ForeignKey(db_column='cod_usu', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'op_frota_indisp_apontamento_promax',
                'managed': True,
            },
        ),
    ]
