# Generated by Django 3.0.5 on 2023-09-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frota_disponibilidade_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apontamento_promax',
            table='ger_indisp_frota_apontamento_promax',
        ),
        migrations.AlterModelTable(
            name='frota_contratada',
            table='ger_indisp_frota_contratada',
        ),
        migrations.AlterModelTable(
            name='grupo_indisponibilidade',
            table='ger_indisp_frota_grupo_indisponibilidade',
        ),
        migrations.AlterModelTable(
            name='sigla_status_disponibilidade_frota',
            table='ger_indisp_frota_siglas_status',
        ),
    ]
