# Generated by Django 3.2.21 on 2023-10-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_5s',
            fields=[
                ('id_cadastro_5s', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('desc_filial', models.CharField(blank=True, max_length=20, null=True)),
                ('matricula', models.IntegerField(blank=True, null=True)),
                ('placa', models.CharField(blank=True, max_length=12, null=True)),
                ('nome_avaliador', models.CharField(blank=True, max_length=20, null=True)),
                ('mapa', models.CharField(blank=True, max_length=20, null=True)),
                ('cabine_livre', models.CharField(blank=True, max_length=4, null=True)),
                ('doc_lugar_adequado', models.CharField(blank=True, max_length=4, null=True)),
                ('estofado_bom', models.CharField(blank=True, max_length=4, null=True)),
                ('aparelho_trk_bom', models.CharField(blank=True, max_length=4, null=True)),
                ('baias_bom', models.CharField(blank=True, max_length=4, null=True)),
                ('notas_organizadas', models.CharField(blank=True, max_length=4, null=True)),
                ('chapatex_organizados', models.CharField(blank=True, max_length=4, null=True)),
                ('plast_papel_segregados', models.CharField(blank=True, max_length=4, null=True)),
                ('pallets_bom', models.CharField(blank=True, max_length=4, null=True)),
                ('vasilhames_separados', models.CharField(blank=True, max_length=4, null=True)),
                ('cabine_limpa', models.CharField(blank=True, max_length=4, null=True)),
                ('baias_limpas', models.CharField(blank=True, max_length=4, null=True)),
                ('eqpe_saber_func_limp', models.CharField(blank=True, max_length=4, null=True)),
                ('eqpe_saber_func_s', models.CharField(blank=True, max_length=4, null=True)),
                ('eqpe_saber_func_rotina_aud', models.CharField(blank=True, max_length=4, null=True)),
                ('eqpe_recorda_gaps', models.CharField(blank=True, max_length=4, null=True)),
                ('eqpq_saber_prog_reconhecimento', models.CharField(blank=True, max_length=4, null=True)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'op_seguranca_5s',
                'managed': True,
            },
        ),
    ]
