# Generated by Django 3.2.21 on 2023-10-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_5s_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro_5s',
            name='matricula',
        ),
        migrations.AddField(
            model_name='cadastro_5s',
            name='ajudante_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cadastro_5s',
            name='ajudante_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cadastro_5s',
            name='data_lancamento',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro_5s',
            name='matricula_motorista',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
