# Generated by Django 3.0.5 on 2024-08-30 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_app', '0005_liberacao_usuario_projeto_benner_cod_empresa'),
        ('estrut_org_app', '0004_filial_tem_calculo_rv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Exec_Processo',
            fields=[
                ('cod_status_exec_processo', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_status_exec_processo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'op_ti_painel_status_exec_processos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Processo',
            fields=[
                ('cod_tipo_processo', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_tipo_processo', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'op_ti_painel_tipos_processos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('cod_processo', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('desc_processo', models.CharField(max_length=30)),
                ('periodicidade', models.CharField(max_length=30)),
                ('data_desativacao', models.DateField(blank=True, null=True)),
                ('hora', models.IntegerField(blank=True, default=0, null=True)),
                ('eh_ativo', models.IntegerField(blank=True, default=0, null=True)),
                ('cod_atividade', models.ForeignKey(blank=True, db_column='cod_atividade', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Atividade')),
                ('cod_usu', models.ForeignKey(blank=True, db_column='cod_uso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
                ('tipo_processo', models.ForeignKey(blank=True, db_column='cod_tipo_processo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ti_painel_processos_automaticos_app.Tipo_Processo')),
            ],
            options={
                'db_table': 'op_ti_painel_processos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Execucao_Processo',
            fields=[
                ('cod_exec_processo', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('obs_exec_processo', models.CharField(max_length=300)),
                ('data', models.DateField(blank=True, null=True)),
                ('hora_inicio_exec', models.DateTimeField(blank=True, null=True)),
                ('hora_fim_exec', models.DateTimeField(blank=True, null=True)),
                ('cod_status_exec_processo', models.ForeignKey(blank=True, db_column='cod_status_exec_processo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ti_painel_processos_automaticos_app.Status_Exec_Processo')),
            ],
            options={
                'db_table': 'op_ti_painel_exec_processos',
                'managed': True,
            },
        ),
    ]
