# Generated by Django 3.0.5 on 2024-09-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti_painel_processos_automaticos_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='tipo_processo',
            new_name='cod_tipo_processo',
        ),
        migrations.AlterField(
            model_name='processo',
            name='desc_processo',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='processo',
            name='periodicidade',
            field=models.CharField(max_length=1),
        ),
    ]
