# Generated by Django 3.0.5 on 2024-09-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estrut_org_app', '0004_filial_tem_calculo_rv'),
        ('usuario_app', '0005_liberacao_usuario_projeto_benner_cod_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCO_Tipo_Multa',
            fields=[
                ('cod_tipo_multa', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('desc_multa', models.CharField(editable=False, max_length=50)),
            ],
            options={
                'db_table': 'ger_cco_tipo_multas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CCO_Multas',
            fields=[
                ('data_inclusao', models.DateField(auto_created=True, auto_now=True)),
                ('cod_multa_antt', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('placa_multa', models.CharField(max_length=12)),
                ('num_auto_infracao', models.CharField(blank=True, max_length=20, null=True)),
                ('data_auto', models.DateField(blank=True, null=True)),
                ('cod_infracao', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('data_recebe_multa_cco', models.DateField(blank=True, null=True)),
                ('data_recebe_multa', models.DateField(blank=True, null=True)),
                ('local_multa', models.CharField(blank=True, max_length=30, null=True)),
                ('data_pag_multa', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('valor_pagar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nome_condutor', models.CharField(blank=True, max_length=30, null=True)),
                ('obs', models.CharField(blank=True, max_length=500, null=True)),
                ('cod_projeto', models.ForeignKey(db_column='cod_projeto', on_delete=django.db.models.deletion.DO_NOTHING, to='estrut_org_app.Projeto')),
                ('cod_tipo_multa', models.ForeignKey(db_column='cod_tipo_multa', on_delete=django.db.models.deletion.CASCADE, to='cco_multas_app.CCO_Tipo_Multa')),
                ('cod_usu', models.ForeignKey(blank=True, db_column='cod_usu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_app.Usuario')),
            ],
            options={
                'db_table': 'ger_cco_multas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CCO_Anexos',
            fields=[
                ('cod_anexo_cco', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('caminho_anexo', models.CharField(blank=True, max_length=100)),
                ('tipo_anexo', models.CharField(blank=True, max_length=20)),
                ('cod_multa_antt', models.ForeignKey(db_column='cod_multa_antt', on_delete=django.db.models.deletion.CASCADE, to='cco_multas_app.CCO_Multas')),
            ],
            options={
                'db_table': 'ger_cco_anexos',
                'managed': True,
            },
        ),
    ]
