from django.urls import path

from apps.plan_controle_fat_2art_terc_app import views

urlpatterns = [
    path('acessa_form_gerar_pag_2art_terc', views.Form_Gerar_Pag_2Art_View.as_view(),
         name='acessa_form_gerar_pag_2art_terc'),
    path('povoa_cb_benef_pesq_mapas_terc', views.Componente_Benef_Terc_View.as_view(),
         name='povoa_cb_benef_pesq_mapas_terc'),
    path('pesq_mapas_terceiros', views.Mapas_Terc_2Art_View.as_view(),
         name='pesq_mapas_terceiros'),
    path('altera_status_mapa_2art_terc_financ', views.Mapas_Terc_2Art_View.as_view(),
         name='altera_status_mapa_2art_terc_financ'),
    path('retona_placas_para_inativacao_do_benner', views.Btn_Form_Gerar_Pag_2Art_View.as_view(),
         name='retona_placas_para_inativacao_do_benner'),
    path('altera_status_igual_ao_benner_mapa_placas_2art_terc_financ', views.Btn_Form_Gerar_Pag_2Art_View.as_view(),
         name='altera_status_igual_ao_benner_mapa_placas_2art_terc_financ'),
    path('retona_placas_nao_cadastradas_periodo_fat_terceiro', views.Btn_Form_Gerar_Pag_2Art_View.as_view(),
         name='retona_placas_nao_cadastradas_periodo_fat_terceiro'),
    path('sincronizar_dados_placa_benef_com_benner', views.Btn_Form_Gerar_Pag_2Art_View.as_view(),
         name='sincronizar_dados_placa_benef_com_benner'),
    path('vincular_placa_2art_cad_placa_terc', views.Btn_Form_Gerar_Pag_2Art_View.as_view(),
         name='vincular_placa_2art_cad_placa_terc'),
    path('atualiza_frete_mapas_pendentes_terc', views.Btn_Form_Gerar_Pag_2Art_View.as_view(),
         name='atualiza_frete_mapas_pendentes_terc'),
    path('retorna_dados_2art_terc_agrupado_por_beneficiario', views.Form_Pag_Mapas_Terc_2Art_Views.as_view(),
         name='retorna_dados_2art_terc_agrupado_por_beneficiario'),
    path('confirma_pag_beneficiario', views.Form_Pag_Mapas_Terc_2Art_Views.as_view(),
             name='confirma_pag_beneficiario'),
    path('retorna_registros_lanc_2art_terc_do_mapa', views.Form_Lanc_Terc_2Art_View.as_view(),
         name='retorna_registros_lanc_2art_terc_do_mapa'),
    path('povoa_listTipoOcorrenciaLanc2ArtTerc_formLanc2ArtTerc',
         views.Comp_Select_Tipo_Ocorrencias_Lanc_2Art_Terc_View.as_view(),
         name='povoa_listTipoOcorrenciaLanc2ArtTerc_formLanc2ArtTerc'),
    path('salva_registro_lanc_2art_terc', views.Form_Lanc_Terc_2Art_View.as_view(),
         name='salva_registro_lanc_2art_terc'),
    path('desativa_lanc_reg_2art_terc_financ/<int:pk>/', views.Form_Lanc_Terc_2Art_View.as_view(),
        name='desativa_lanc_reg_2art_terc_financ'),
    path('acessa_form_cad_placa_2art_terc', views.Form_Cad_Placa_2Art_Terc_View.as_view(),
        name='acessa_form_cad_placa_2art_terc'),
    path('retorna_cad_beneficiario_terceiros_projeto_selecionado', views.Form_Cad_Beneficiarios_View.as_view(),
         name='retorna_cad_beneficiario_terceiros_projeto_selecionado'),
    path('atualiza_comp_benef_benner_cad_placa_terc', views.Comp_Beneficiarios_Terc_2Art_View.as_view(),
         name='atualiza_comp_benef_benner_cad_placa_terc'),
    path('salva_registro_cad_beneficiario_terceiros', views.Form_Cad_Beneficiarios_View.as_view(),
         name='salva_registro_cad_beneficiario_terceiros'),
    path('desativa_ativa_registro_cad_beneficiario_terceiros/<int:pk>/', views.Form_Cad_Beneficiarios_View.as_view(),
         name='desativa_ativa_registro_cad_beneficiario_terceiros'),
    path('salva_registro_cad_placa_terceiros', views.Form_Cad_Placa_2Art_Terc_View.as_view(),
         name='salva_registro_cad_placa_terceiros'),
    path('pesquisa_registros_cad_placa_terceiros', views.Tab_Cad_Placa_2Art_Terc_View.as_view(),
         name='pesquisa_registros_cad_placa_terceiros'),
    path('retorna_qtd_mapas_pagos_vinculados_cad_placa', views.Tab_Cad_Placa_2Art_Terc_View.as_view(),
         name='retorna_qtd_mapas_pagos_vinculados_cad_placa'),
    path('exclui_registro_cad_placa_terceiros/<int:pk>/', views.Tab_Cad_Placa_2Art_Terc_View.as_view(),
         name='exclui_registro_cad_placa_terceiros'),
    path('pesquisa_data_origem_replicacao_cad_placa_spot', views.Form_Replica_Cad_Placas_2Art_Terc_View.as_view(),
         name='pesquisa_data_origem_replicacao_cad_placa_spot'),
    path('replica_registro_cad_placa_terceiros', views.Form_Replica_Cad_Placas_2Art_Terc_View.as_view(),
         name='replica_registro_cad_placa_terceiros'),
    path('form_pesq_cad_frete_terceiros', views.Form_Cad_Fretes_Terc_View.as_view(),
         name='form_pesq_cad_frete_terceiros'),
    path('salva_registro_cad_frete_spot', views.Form_Cad_Fretes_Terc_View.as_view(),
         name='salva_registro_cad_frete_spot'),
    path('pesquisa_registros_cad_frete_spot', views.Tab_Cad_Fretes_Terc_View.as_view(),
         name='pesquisa_registros_cad_frete_spot'),
    path('retorna_qtd_mapas_pagos_vinculados_cad_frete_spot', views.Tab_Cad_Fretes_Terc_View.as_view(),
         name='retorna_qtd_mapas_pagos_vinculados_cad_frete_spot'),
    path('exclui_registro_cad_frete_spot/<int:pk>/', views.Tab_Cad_Fretes_Terc_View.as_view(),
         name='exclui_registro_cad_frete_spot'),
    path('pesquisa_data_origem_replicacao_cad_frete_spot', views.Form_Replica_Cad_Frete_2Art_Terc_View.as_view(),
         name='pesquisa_data_origem_replicacao_cad_frete_spot'),
    path('replica_registro_cad_frete_spot', views.Form_Replica_Cad_Frete_2Art_Terc_View.as_view(),
         name='replica_registro_cad_frete_spot'),
    path('form_importa_arquivo_fat_terc', views.Form_Importa_Arquivo_Fat_Terc_View.as_view(),
         name='form_importa_arquivo_fat_terc'),
    path('importa_arquivo_lanc_terc_financ', views.Form_Importa_Arquivo_Fat_Terc_View.as_view(),
         name='importa_arquivo_lanc_terc_financ'),
    path('form_relatorio_pagamento_terceiros', views.Form_Relatorio_Pagamentos_Terc_View.as_view(),
         name='form_relatorio_pagamento_terceiros'),
    path('retorna_pagamentos_terceiro', views.Tab_Relatorio_Pagamentos_Terc_View.as_view(),
         name='retorna_pagamentos_terceiro'),
    path('retorna_mapas_pagamento_selecionado', views.Tab_Relatorio_Mapas_Pagamentos_Terc_View.as_view(),
         name='retorna_mapas_pagamento_selecionado'),
    path('desfaz_pagamento_mapas_beneficiario_terc/<int:pk>/', views.Tab_Relatorio_Mapas_Pagamentos_Terc_View.as_view(),
         name='desfaz_pagamento_mapas_beneficiario_terc'),
    path('gera_rel_pdf_mapas_pagos_terc_por_beneficiario', views.Pdf_Rel_Pagamento_Terc.as_view(),
         name='gera_rel_pdf_mapas_pagos_terc_por_beneficiario'),
    path('gera_rel_pdf_acres_desc_pagamento_mapas_terc', views.Pdf_Rel_Acres_Desc_Pagamento_Terc.as_view(),
         name='gera_rel_pdf_acres_desc_pagamento_mapas_terc'),
    path('atualiza_dados_reg_2art_terc_financ', views.Form_Gerar_Pag_2Art_View.as_view(),
         name='atualiza_dados_reg_2art_terc_financ'),

]